### ISSUE TITLE
SteamVR 2.2 + VIU 1.10.3.0 controller binding example blows up

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#100]
SteamVR unity plugin: 2.2
SteamVR Beta 1.3.7 
VIU unity plugin: 1.10.3.0
Unity: 2019.2.0a6
Hardware: Vive Pro + 1.0 base stations + Knuckles

set up a fresh project, import SteamVR 2.2 and VIU 1.10.3.0 (current release for both) 

open example 7, on play the error below shows up, and when you click on add device, no devices show up in selection dialog.

![image](https://user-images.githubusercontent.com/140221/54092146-0e287f80-435f-11e9-9fbb-1df96204dc34.png)

**Comment by chengnay** [comment]
@wirelessdreamer You can have a temporary fix by adding a line of code to your project.

In Assets/HTC.UnityPlugin/ViveInputUtility/Scripts/ViveRole/RoleMaps/BodyRole.cs,
Line 58,
UnmappingAll();

_if (!VRModule.IsValidDeviceIndex(VRModule.HMD_DEVICE_INDEX)) { return; }_ <--- Add this line

MappingRoleIfUnbound(BodyRole.Head, 0u);

**Comment by wirelessdreamer** [comment]
That fixed it. Thanks. Feel free to re open this if you need it to track the bug for later.
