### ISSUE TITLE
Count of Active controllers in binding interface no longer shows up

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#109]
![image](https://user-images.githubusercontent.com/140221/55601211-c7dff980-572d-11e9-9751-b7e9a2bcae68.png)

This issue exists in both the Asset store version, and the current code on Git

**Comment by wirelessdreamer** [comment]
To reproduce bind controllers, stop the example binding scene, and hit play again, then the counts disappear.

Removing or adding another binding makes the count show up again.

**Comment by chengnay** [comment]
@wirelessdreamer The latest VIU package fixed this issue. Please try it out, thanks!

**Comment by wirelessdreamer** [comment]
Resolved. Thanks :)
