### ISSUE TITLE
Default Teleport example scene - Adjusting max teleport distance is broken

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#111]
Adjust the Far Distance on Vive Raycaster from 20 to 80, the max distance for teleport still stays at 20, limiting the max distance for teleporting.

**Comment by chengnay** [comment]
@wirelessdreamer To increase the max distance for teleport is not adjusting the Far Distance.
You need to adjust the ProjectileGenerator's Velocity(increasing) or Gravity Y axis value(decreasing).

**Comment by wirelessdreamer** [comment]
Thanks
