### ISSUE TITLE
WaveVR SDK is missing #if UNITY_ANDROID ... #endif defines around its code

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#119]
multi platform compilation of projects that include wavevr sdk fail. wrapping files from it so its only included on android would be a clean solution.

**Comment by chengnay** [comment]
How could I reproduce this issue?
How many SDK you have imported for your project?

**Comment by wirelessdreamer** [comment]
import WaveVR SDK into a project, target windows with the project and try to compile it.

**Comment by chengnay** [comment]
It is not recommended to have other platform's SDKs included in your project while compiling.
Unused SDKs will take up space while you build your project into an executable file.
If you still think adding #if UNITY_ANDROID ... #endif to WaveVR SDK is necessary, please submit a case for them in [WaveVR SDK forum](https://community.viveport.com/t5/Vive-Wave-SDK/bd-p/vive-wave-sdk).

**Comment by wirelessdreamer** [comment]
having the platform sdk so its pre-processor is what enables in for its platform helps to negate that issue, as none of the code for it is is compiled into the resulting binary :)
