### ISSUE TITLE
Vive tracker was detected as controller in role binding interface

### ISSUE THREAD

**Issue by neku7474** [ViveSoftware/ViveInputUtility-Unity#122]
I used vive role binding interface.
But sometime Vive tracker was detected as vive controller in role binding interface and the tracker's rotation changed.

Is there any solution?

**Comment by chengnay** [comment]
Which version of VIU are you using?
Please list the version of Unity and any SDK that you used too, thanks!

**Comment by neku7474** [comment]
I have solved this issue.
It was steamVR issue.
I changed Tracker's role to "Disable".
