### ISSUE TITLE
Show RIft s / Quest controller models when using those controllers

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#126]
Currently the previous generation of controller is shown for those platforms. Also add platform defines for both platforms.

**Comment by chengnay** [comment]
@wirelessdreamer Latest GitHub can support Oculus Quest.
I cannot get Oculus Rift S device yet, cannot finish adding this device.

**Comment by wirelessdreamer** [comment]
Resolved.
