### ISSUE TITLE
UGUI Example scene locks up on QUEST when clicking on text input field

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#131]
import viu, load UI example scene, push to quest, click on text input field. Quest locks up with 3 dots

**Comment by chengnay** [comment]
@wirelessdreamer I just checked that issue, and it is not caused by VIU.
InputField is the root cause to this issue, but not sure why it does not happen in Oculus Go.

**Comment by wirelessdreamer** [comment]
I have an open issue with unity on it. I haven't seen any updates yet
though.

**Comment by wirelessdreamer** [comment]
Fixed upstream in unity.
