### ISSUE TITLE
Render queue changed when hitting an object

### ISSUE THREAD

**Issue by JerryLetehen** [ViveSoftware/ViveInputUtility-Unity#133]
**Steps:**
    1. Open any tutorial where the lasers are
    2. Look through the laser when it hits an object and when it doesn't
 
**Factual:** When the laser hits an object objects behind are visible. When it doesn't, the objects are hidden.
**Expected:** Objects behind the laser are always visible.
See attachments.
![Screenshot_21](https://user-images.githubusercontent.com/35923264/60875691-0e6c5500-a243-11e9-98cf-babffadf0436.png)
![Screenshot_22](https://user-images.githubusercontent.com/35923264/60875692-0e6c5500-a243-11e9-9109-56e6af69db15.png)

**Comment by chengnay** [comment]
@JerryLetehen Could you try editing the shader of the GuideLine to UI/Unlit/Transparent?
![image](https://user-images.githubusercontent.com/33050705/61109791-53e58800-a4b8-11e9-8b37-14a03d0adf2a.png)

**Comment by JerryLetehen** [comment]
@chengnay doesnt fix the issue

**Comment by chengnay** [comment]
@JerryLetehen Could you try adjusting the order in layer for the Guideline?
![image](https://user-images.githubusercontent.com/33050705/61262932-bb058400-a7b9-11e9-8351-498a20b16d17.png)

Is this what you are looking for?

**Comment by JerryLetehen** [comment]
@chengnay Looks good. I think that resolves this issue. Thank you
