### ISSUE TITLE
Colliders influence height of camera (head) position

### ISSUE THREAD

**Issue by skahlert** [ViveSoftware/ViveInputUtility-Unity#134]
The camera position seems to adjust height, depending on colliders directly below the camera position. For example if the player moves the head forward, just above a ascending stair, the camera jumps up a few centimeters, without the user triggering a teleport.
It seems like the camera always tries to stay above a certain distance of the first collider hit, but there is no way I found to influence, which colliders are evaluated.
In general I would expect the camera always to stay above the reference point of the rig (where I last teleported to).

**Comment by chengnay** [comment]
@skahlert Which device you are using?
Please provide the version of Unity, Plugin and VIU.
Could you also provide a sample project or a short video?

**Comment by skahlert** [comment]
1. The device used is the Vive Focus Plus. But I can replicate it also through the simulator (see attached video).
2. I did not add a collider to the Camera of the ViveRig prefab, no...
3. VIU Version: 1.10.4, Unity: 2019.1.3f1, WaveSDK: 3.0.2
4. Video is [here](https://www.dropbox.com/s/juzyq3njjfrmafd/error_1.mp4?dl=0). The project is a bit large, though. I'll try to make a smaller one, that replicates the issue.

**Comment by skahlert** [comment]
While creating the test-project I found that the VRTK teleporter seems to hijack the camera and snap it to the floor. I was not aware of this sideeffect. So no issue with VIU.
Sorry, for the confusion.
