### ISSUE TITLE
WaveVR ignores unity provided Android SDK and JDK

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#137]
Wave SDK throws errors when trying to enable WaveVR support in unity when using provided Unity android build tools, which is the normal Unity android workflow for the past few releases.

**Comment by chengnay** [comment]
@wirelessdreamer Which Unity version you are using? Let me duplicate on my side to see what I can do to fix it.

**Comment by wirelessdreamer** [comment]
2019.2.0f1

**Comment by chengnay** [comment]
Could you show me your settings?
![image](https://user-images.githubusercontent.com/33050705/63409192-43afb980-c423-11e9-9ad8-60eac29d6495.png)

**Comment by chengnay** [comment]
I just build success, so I might need more information from you.
This is my External Tools settings.
![image](https://user-images.githubusercontent.com/33050705/63414404-5ed3f680-c42e-11e9-9a05-e4fdd16cadb2.png)

Please share your settings and also the build error log.
By the way, I am using WaveSDK 3.0.2, what about yours?

**Comment by wirelessdreamer** [comment]
I pulled WaveVR support from the projects I am working with a while ago, and sent back the test device I was using. so I won't have any useful feedback for you on this.
