### ISSUE TITLE
Please ship with ASMDEF

### ISSUE THREAD

**Issue by MSFX** [ViveSoftware/ViveInputUtility-Unity#139]
Could you please ship a version with asmdef setup, currently with the number of editor directories present it's not really practical creating so many assemblies
Thanks

**Comment by chengnay** [comment]
@MSFX Sorry, we are not very familiar with ASMDEF.
Could you explain more how to improve this part?
How many Plugin SDKs you have imported?

**Comment by MSFX** [comment]
Thanks for the reply.  You can find more info [here](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html). 

The main issue is with the "Editor" folders you have which should be compiled into a seperate editor assembly so they can't be within directories added under an assembly, so there either needs to be an assembly per Editor directory or you place all Editor scripts into one single Editor directory, which is probably the better approach.   My project has 5 plugins and 6 assemblies.

**Comment by chengnay** [comment]
@MSFX I tried to add ASMDEF to some of the Editor folders, and I will get bunch of compile errors.
It is because in VIU, script files will reference to other script files in other directories.
Do you have any idea how to approach to resolve this issue?

**Comment by MSFX** [comment]
So if files within one assembly have to reference scripts within another assembly you have to add that assembly to the list of referenced assemblies shown in the inspector when you select the assembly... hope that makes sense??

**Comment by MSFX** [comment]
have you managed to resolve this?

**Comment by chengnay** [comment]
Sorry that VIU might not be able to ship with ASMDEF because VIU supports multi SDKs.
It is hard to add dependencies for multi SDKs and it will break if either one doesn't existed in the project.

**Comment by brunocoimbrar** [comment]
@chengnay in Unity 2019 they added the new Version Defines, which solves the multi SDK dependencies issue. It could be an opt-in feature by having a button to generate the ASMDEFs in the Preferences menu.

I can do that myself and do a pull request, but wanted to first check if this would be an acceptable approach for you, as it will add an extra maintenance layer.

**Comment by brunocoimbrar** [comment]
Actually Version Defines were not needed as the scripting defines symbols still work with ASMDEF, but due some cross references between VRModule and ViveInputUtility folders it requires assembly definition references to work properly, which is only available on 2019.2.

**Comment by chengnay** [comment]
> Actually Version Defines are not needed as the scripting defines symbols still work with ASMDEF, but due some cross references between VRModule and ViveInputUtility folders it requires assembly definition references to work properly, which is only available on 2019.2.

Thanks for your information, I will take a look at it.

**Comment by chengnay** [comment]
@MSFX In the latest [VIU v1.11.0](https://github.com/ViveSoftware/ViveInputUtility-Unity/tree/v1.11.0-upm) already shipped with ASMDEF. This upm version will be updated to Unity Package Manager in the future.
ASMDEF is not included in the Unity Asset Store version.
