### ISSUE TITLE
OculusVRModule.cs `Pose' is an ambiguous reference 9 (Unity 2017.2.0.b8)

### ISSUE THREAD

**Issue by bartburkhardt** [ViveSoftware/ViveInputUtility-Unity#14]
When using Unity 2017.2.0b8 I get following error;

Assets/HTC.UnityPlugin/VRModule/Modules/OculusVRModule.cs(107,24): error CS0104: `Pose' is an ambiguous reference between `HTC.UnityPlugin.PoseTracker.Pose' and `UnityEngine.Pose'

To correct I changed into PoseTracker.Pose
Then I get errer that VRSettings can't be found. I changed it into XRSettings
Then again more Pose errors, corrected again using PoseTracker.Pose
Then I get error VRDevice can't be found. I changed it into XRDevice

**Comment by lawwong** [comment]
Thanks for the report, we missed the OculusVRModule.cs.

Also you can use type alias like
```
using UnityEngine;
using Pose = HTC.UnityPlugin.PoseTracker.Pose;
```
so you can use Pose in your script.

**Comment by bartburkhardt** [comment]
I still get 4 errors after these changes;
Assertion failed: Assertion failed on expression: 'false && "unsupported texture format"
Assertion failed: Assertion failed on expression: 'false && "unsupported texture format"
Assertion failed: Assertion failed on expression: 'false && "unsupported texture format"
Assertion failed: Assertion failed on expression: 'false && "unsupported texture format"

**Comment by lawwong** [comment]
Can you help allocate the errors? We can't reproduce the errors on Unity 2017.2.0f3 with OVR v1.20.0
