### ISSUE TITLE
VIU Specific Action Sets and Default Bindings

### ISSUE THREAD

**Issue by MSFX** [ViveSoftware/ViveInputUtility-Unity#140]
![errors](https://user-images.githubusercontent.com/296612/64450942-06ae1d00-d0db-11e9-8620-457bd305ce0c.PNG)

Unity 2018.2.14f1
SteamVR 2.3.2
VUI 1.10.4

From [this page](https://github.com/ViveSoftware/ViveInputUtility-Unity/wiki/SteamVR-Input-System-Compatibility) I'm not getting the second step about importing/aaplying VUI project settings... how can I force this please?

Thanks
M

**Comment by chengnay** [comment]
@MSFX Could you try the latest build from GitHub?
Sorry, we have not updated latest build to Asset Store.

**Comment by MSFX** [comment]
Ahhhh yes unchecking Vive in VUI settings gave me the Recommended Settings button, thanks! :)
