### ISSUE TITLE
Quest button state not tracking properly

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#142]
Logcat results from button presses

2019-09-23 13:24:45.725 11379-11379/com.Test.test W/InputDeviceManager: SetRemoteLatchedButtonState: failed to find device d5cee8ddffffffff

This is using the B button. Code works fine on Rift S, on quest it does not.

This was a workaround I tried because GetPress was experiencing the above issue, so the button i had bound to move wasn't working. 

Related code: 

        if (ViveInput.GetPressDown(viveRole, moveButton)){
            Debug.Log("moving");
            moveState = true;
        }

        if(ViveInput.GetPressUp(viveRole, moveButton)) {
            Debug.Log("not moving");
            moveState = false;
        }

        Move(moveState); // Move must be called every frame

**Comment by chengnay** [comment]
@wirelessdreamer Which version of Oculus SDK and VIU you're using?
And, Unity version.

**Comment by chengnay** [comment]
@wirelessdreamer Which button you use for moveButton?
For B button, it should be ControllerButton.Menu.

**Comment by wirelessdreamer** [comment]
With current updated libraries and packages I'm not longer seeing this. I'm not sure what the cause was, but its not a VIU issue.
