### ISSUE TITLE
Using VIU with WaveVR 3.1.1 beta

### ISSUE THREAD

**Issue by rikkuporta** [ViveSoftware/ViveInputUtility-Unity#143]
Is there a possibility to use the new WaveVR SDk, like a VIU preview or beta for it?
There is an error is WaveVRModule:641 
`if (!WaveVR.Instance.isSimulatorOn || WaveVR_Utils.WVR_GetDegreeOfFreedom_S() == (int)WVR_NumDoF.WVR_NumDoF_6DoF) { return; }`
where isSimulatorOn and WVR_GetDegreeOfFreedom_S() are not available anymore

**Comment by chengnay** [comment]
@rikkuporta What's the version of VIU you are using?
Did you try using the one in GitHub?

**Comment by rikkuporta** [comment]
Thanks, it is working with the Version from Github ('ve been using the one from the Asset Store)

**Comment by chengnay** [comment]
@rikkuporta We will be updating the version on Asset Store soon.
Sorry for the inconvenience.
