### ISSUE TITLE
VIU deactivating Camera on ViveRIg on Start

### ISSUE THREAD

**Issue by rikkuporta** [ViveSoftware/ViveInputUtility-Unity#145]
I'm using the newest Version of the VIU Asset her from Github and the WaveVR 3.1.1 Beta SDK on Windows 10 with Unity 2018.4.2f1.
I have a Scene with nothing inside except for the ViveRig. When I start the Scene, there is a moment where the camera is activated/enabled, then the Camera is deactivated/disabled. 

It does not matter if Virtual Reality Supported is ticked on or off in the XR Settings.
The Box in WaveVR to Enable Automatic VR is enabled.
WaveVR is also in VIU Settings enabled

**Comment by chengnay** [comment]
@rikkuporta After the Camera is deactivated/disabled, it will keep disabling or it will activate/enable again?

**Comment by rikkuporta** [comment]
No, after I manually activate it, it stays activated
This also happens in the example 04.Teleport.
I am referring to the ViveRig prefab

![image](https://user-images.githubusercontent.com/3002584/66148206-ab574800-e610-11e9-88ed-8017fc167e24.png)

**Comment by chengnay** [comment]
@rikkuporta This is not an issue.
The actual camera is activated on Eye Both, so under Camera GameObject's Camera will be disabled.

**Comment by rikkuporta** [comment]
You are right, that is indeed the case. Thanks
