### ISSUE TITLE
SendMessage cannot be called during Awake, CheckConsistency, or OnValidate spam

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#148]
![image](https://user-images.githubusercontent.com/140221/66452049-00d68f00-ea2d-11e9-9992-560de47267e6.png)

I've been seeing page after page of these warnings in multiple projects for a while. any idea where they come from?

**Comment by chengnay** [comment]
@wirelessdreamer Which version of Unity Editor are you using?

**Comment by wirelessdreamer** [comment]
2019.2.7.f2

**Comment by chengnay** [comment]
@wirelessdreamer I might need additional information,
Which platform you are targeting? PC?
Do you see these warning messages in VIU example scene?
Which plugin SDKs you have imported into your project?
Could you provide a sample project that will spam these messages for debugging?

**Comment by wirelessdreamer** [comment]
These warnings came from an if block for another unity version. we removed the block and they went away. Another dev on our team took care of it a few weeks ago, and I forgot about this issue.
