### ISSUE TITLE
When i click an UI button in Unity shutsdown OpenVR and the application

### ISSUE THREAD

**Issue by dpggit** [ViveSoftware/ViveInputUtility-Unity#149]
I use Unity 2018.3 and the last viveinpututility in the unity asset store but just clicking a button shuts down opevr, i receive that message in the Unity console. I am using steamvr and i moved the right and left gameobjects with the component vive role setters to the left and right hands, but somehow the click makes openvr shutdown

**Comment by chengnay** [comment]
@dpggit Could you provide more detailed information (step by step or screenshots)? or a sample project that can reproduce this error?

**Comment by dpggit** [comment]
I move each object with the component "vive role setters" inside each the steamvr hand and delete the rest, then i press a button with a onclick event and then application stops and i receive the openvr shutdown message in unity console

**Comment by dpggit** [comment]
If i disable the script "canvas raycast target" application doesnt close but

**Comment by dpggit** [comment]
I didnt want to close this issue

**Comment by chengnay** [comment]
@dpggit For example by taking the Simple Sample scene from SteamVR plugin,
I will add "vive role setters" to controller left and right? Is that correct?
![image](https://user-images.githubusercontent.com/33050705/66882842-7975b680-effe-11e9-82ba-03cf26701bc1.png)

Your canvas, can I refer to Sphere which is in this scene?
And add "canvas raycast target" to Sphere?

**Comment by dpggit** [comment]
I have finally solved , i had the vive eventsystem script added in other object, i had it duplicated

**Comment by chengnay** [comment]
I will close this issue, if you encounter issue, please let me know, thanks!
