### ISSUE TITLE
GetAngularVelocity does not work

### ISSUE THREAD

**Issue by skelder** [ViveSoftware/ViveInputUtility-Unity#152]
VivePose.GetAngularVelocity returns 0,0,0 vector3. 
Is there any specific way it should be accessed?

**Comment by chengnay** [comment]
@skelder Which device you are using?
Could you provide more detailed information?
For which platform(PC, Android, Oculus or OpenVR devices), any other SDKs(versions) imported to your project and which version of VIU?

**Comment by skelder** [comment]
Sorry for lack of information

Devices used for testing: Vive Pro with 2 vive controllers
OS: windows PC
Additional SDK: oculus integration due to the fact that I have to ship this to oculus quest in the end
And No steamVR if its important
VIU version : 1.10.4.0

**Comment by skelder** [comment]
I tested with newest version 1.10.6 as well but it just kept on reporting 0 vector
No matter where I checked on Update or FixedUpdate

**Comment by chengnay** [comment]
@skelder What did you check in VIU Settings?
I don't think Vive Pro works with Oculus Integration Plugin.

**Comment by skelder** [comment]
Great now it seems to work! Thanks a lot.

Was there any specific reason to not include the angular velocity in those files in the latest release or was it just a omission during the update?

**Comment by skelder** [comment]
Also this is not really related to the problem, but I was curious about the difference between the Getvelocity and the GetVelocityEx. 

I could not find the documentations about it and looking at the code just confused me even further.

What is the exact difference between them?

**Comment by chengnay** [comment]
> Great now it seems to work! Thanks a lot.
> 
> Was there any specific reason to not include the angular velocity in those files in the latest release or was it just a omission during the update?

We didn't notice that Unity provides angular velocity API in Unity 2017.2 and newer version.


> Also this is not really related to the problem, but I was curious about the difference between the Getvelocity and the GetVelocityEx.
> 
> I could not find the documentations about it and looking at the code just confused me even further.
> 
> What is the exact difference between them?

API ending with Ex is a generic API which can use for TrackerRole.
For example,
VivePose.GetAngularVelocity(TrackerRole.Tracker1), this will have compile error
But,
VivePose.GetAngularVelocityEx(TrackerRole.Tracker1) will work

**Comment by skelder** [comment]
Thanks a lot!
