### ISSUE TITLE
How can disable Vive input utility in Unity

### ISSUE THREAD

**Issue by dpggit** [ViveSoftware/ViveInputUtility-Unity#153]
I have Unity 2018 and Vive input utility window is all the time popping up and slows a lot the computer, its like a virus, how can i disable it?

**Comment by chengnay** [comment]
@dpggit Are you referring to the VIU window is the recommended settings window (please see the below image)?
![image](https://user-images.githubusercontent.com/33050705/67254631-af101900-f4b0-11e9-88ce-be49c137b2a6.png)

**Comment by dpggit** [comment]
Yes, that one

**Comment by chengnay** [comment]
@dpggit This window is recommended settings, there are 2 options to stop this window from popping up,
1. Click Accept All
2. Click Ignore All
I believe if there is NEW recommended settings, this window will pop up again.

**Comment by dpggit** [comment]
I clicked in Accept all and keeps appearing

**Comment by chengnay** [comment]
@dpggit Does it keep appearing with nothing in the list?
Or which item keeps appearing?
Please take a screenshot for me, thanks!

**Comment by dpggit** [comment]
Keeps appearing with the option "Apply VIU action set".
I just have OpenVR added in VR options
I use 2018.3.13f1
I target Windows standalone
Dont know what you mean by Recommended settings, i show you the image of the window
![imagen](https://user-images.githubusercontent.com/10148361/67491897-df54e480-f675-11e9-9bd9-32c84458151b.png)

**Comment by chengnay** [comment]
@dpggit Which version of SteamVR Plugin you have imported?
And, what is your version of VIU?

**Comment by dpggit** [comment]
Steamvr 2.0.1 and VIU 1.10.6

**Comment by chengnay** [comment]
I couldn't reproduce your issue.
After I click on "Ignore All", it will be added to ignore list,
![image](https://user-images.githubusercontent.com/33050705/67538659-58097e80-f712-11e9-8e1d-272adc2ca788.png)
It will only show up again if you remove it from the list.
Are you able to share your project or created a sample project that can reproduce this issue?

**Comment by dpggit** [comment]
If i select ignore all they dont appear again but some actions stop working, if i select accept all the window appears again

**Comment by chengnay** [comment]
Could you provide a sample project that can reproduce the issue? I am not able to reproduce on my PC with Unity 2018.3.13f1 + VIU v1.10.6 + SteamVR Plugin 2.0.1.

**Comment by dpggit** [comment]
Cannot send a sample of the project, and it is too big to send anyways
