### ISSUE TITLE
Vive input utility make all my actions not work anymore

### ISSUE THREAD

**Issue by dpggit** [ViveSoftware/ViveInputUtility-Unity#154]
I had all the actions working and after updating to last version in Unity all my actions dont work anymore. I can see them in vr input but dont work anymore

**Comment by dpggit** [comment]
Found the reason, i see the bindings were deleted, i had to make them again

**Comment by chengnay** [comment]
@dpggit bindings deleted? By who?

**Comment by dpggit** [comment]
By Vive input when i updated

**Comment by chengnay** [comment]
@dpggit Do you have any reproduce steps to share?
Do you think this is an issue or bug?

**Comment by dpggit** [comment]
I just updated to last version and my actions stopped working, and i saw they were unbinded

**Comment by dpggit** [comment]
I have chosen ignore all and now some actions dont work

**Comment by dpggit** [comment]
The only action which works so far is when i click the touchpad, the new action system is really a nightmare, i am having TONS of problems with this system

**Comment by dpggit** [comment]
I reimported viu again and deleted the bindings again, this is a disaster

**Comment by dpggit** [comment]
I see the GetStateDown and GetStateUp dont work

**Comment by chengnay** [comment]
@dpggit Did you upgrade to the latest version of SteamVR Plugin?
I think this issue is related to the VIU's recommended settings window keeps popping up.

**Comment by dpggit** [comment]
No, i use 2.0.1 as i had a lot of problems with other versions

**Comment by chengnay** [comment]
> By Vive input when i updated

VIU will not remove any bindings, please provide a reproduce steps or share a sample project that can reproduce the issue that you mentioned, thanks!

**Comment by dpggit** [comment]
Yes, VIU will remove the bindings, i have made a video, if you tell me a email i can send it to you

**Comment by dpggit** [comment]
Just removed VIU and GetStateDown and GetStateUp started working again, you have serious problems with this app

**Comment by chengnay** [comment]
@dpggit Please email to me at chengnan_yang@htc.com

**Comment by dpggit** [comment]
i have already sent you the video

**Comment by chengnay** [comment]
@dpggit After a quick look at your video, first question is that you basically did not delete the right folder for VIU, HTC.UnityPlugin is the root folder for VIU. Could you try removing VIU cleanly and try again? I suggest It is better to removing htc_viu action set and re-adding with latest VIU.

**Comment by chengnay** [comment]
Here is a [post](https://medium.com/@sarthakghosh/a-complete-guide-to-the-steamvr-2-0-input-system-in-unity-380e3b1b3311) talking about how to use the newer version of SteamVR Plugin,
probably you can try to upgrade your project to a newer version of SteamVR Plugin.

And, I will try to fix the GetStateUp and GetStateDown issue based on newer version of SteamVR Plugin.

**Comment by dpggit** [comment]
I have installed the 2.4.5 steamvr and deleted everythin in htc vive folder related to VIU, not just the ViveInputUtility folder, and keeps deleting my bindings

**Comment by chengnay** [comment]
@dpggit Could you record a video how your bindings are deleted?

**Comment by dpggit** [comment]
i already sent you a video showing how bindings are deleted, fix it if you want

**Comment by chengnay** [comment]
@dpggit From your previous video, what I see is that you are adding your custom bindings to default action set which belongs to SteamVR and not htc_viu, I guess it should be SteamVR which overrides your bindings and not VIU.
The correct way of adding your own custom bindings, you should have to create your own action set and not just adding your actions to others' action set.
I just finished writing a post on [how to setup your custom input bindings](https://github.com/ViveSoftware/ViveInputUtility-Unity/wiki/Setup-Custom-Input-Bindings-for-SteamVR-Input-System), you can try this out.

By the way, it is not I don't want to fix the issue. If it is 100% to reproduce issue on my side, for sure I will fix it. And, your actions are added to other's action set, it is totally out of VIU's control.

**Comment by dpggit** [comment]
All actions belong to steamvr, not just the default ones, but what deletes the bindings its just when i install VIU. I just added the actions through the Steamvr input. Steamvr never replaced my bindings, just VIU. Bindings are persistent, they are saved, just are replaced when install VIU, i already reproduced the issue with steamvr 2.0.1 dont want to delete and recreate my bindings again for 2.4.5 to make a video, but with 2.4.5 bindings were removed too when i installed VIU

**Comment by chengnay** [comment]
Just to clarify your reproduce steps as below, correct me if I miss any steps.
1. Create new project with SteamVR Plugin v2.4.5
2. Add custom actions through SteamVR Input window then save and generate
3. Go to bindings window to bind actions
4. Import VIU from Asset Store
5. Add htc_viu action set
After 5th step, your bindings are deleted?

**Comment by dpggit** [comment]
Just do what i show in the video, i never added a htc_viu action set but any action set you add has the bindings deleted, in any case the actions must be added before importing VIU

**Comment by chengnay** [comment]
@dpggit Could you try launching the bindings window from SteamVR instead of using the "Open binding UI" button from SteamVR Input window?


By pressing the top-left corner on SteamVR,
![image](https://user-images.githubusercontent.com/33050705/68264557-1e2a6780-0084-11ea-9043-562a398425ce.png)
Go to Devices>Controller Settings,
Select your application under "Edit Controller Bindings",
![image](https://user-images.githubusercontent.com/33050705/68264614-5a5dc800-0084-11ea-88d0-2254bac60628.png)
NOTE: You can play your scene then press F5 under Controller Settings window, your application will be at the top on the list

I am not sure if using this method to open the bindings window, it will show different result?

**Comment by dpggit** [comment]
My application doesnt appear in the top of the list, just appears Unity application and not in the top of the list and doesnt show my bindings anyways. With latest Steamvr update now Steamvr doesnt work anymore properly and my hand devices dont work, its something wrong with Steamvr but the errors are 
I get these errors :
NullReferenceException: Object reference not set to an instance of an object
Valve.VR.InteractionSystem.Hand.OnEnable () (at Assets/SteamVR/InteractionSystem/Core/Scripts/Hand.cs:1083)
The line which triggers the null error is : inputFocusAction.enabled = true;
NullReferenceException: Object reference not set to an instance of an object
Valve.VR.InteractionSystem.ControllerButtonHints.OnEnable () (at Assets/SteamVR/InteractionSystem/Hints/Scripts/ControllerButtonHints.cs:108)
The line which triggers the null error is : renderModelLoadedAction.enabled = true;

**Comment by chengnay** [comment]
@dpggit In order to see your application at the top of the list, you need to play your scene in Unity first,
then refresh(pressing F5) under Controller Settings window. That Unity application in the list is not the same as your application that you are developing.
Your application will be same as your project name ending with XXXX[TESTING].

**Comment by dpggit** [comment]
Bindings can be seen again with v2.5.0
