### ISSUE TITLE
SteamVR 2.4.5 actions dont work with VIU

### ISSUE THREAD

**Issue by dpggit** [ViveSoftware/ViveInputUtility-Unity#156]
I have installed SteamVR 2.4.5 and now VIU dont trigger anything in the UI. With SteanVR 2.0.1 i could interact with the different IU elements but now i cant even trigger a button

**Comment by dpggit** [comment]
I see if (!RectTransformUtility.RectangleContainsScreenPoint(graphic.rectTransform, screenCenterPoint, eventCamera)) { continue; } is always false in Raycast method in CanvasRaycastMethod script

**Comment by lihaiyang-xx** [comment]
I have the same problem when upgrate to steamvr 2.4.5

**Comment by chengnay** [comment]
@dpggit @lihaiyang-xx On VIU's example scene, does it works?
Upgrading from SteamVR Plugin 2.0.1 to 2.4.5, did you follow Steam's suggestion?

Upgrading from older versions
Upgrading from anything from 2.1 - 2.3
The location of actions.json and associated bindings has changed. They will get automatically moved from project root to StreamingAssets/SteamVR/

Upgrading from version 2.0
You will need to delete your SteamVR/SteamVR_Input folders, Save and Generate, and then re-set your actions that you've assigned in the editor. You do not need to recreate your actions file or bindings files. This was necessary to support Unity's new serialization in 2018/2019. If you've made changes to your SteamVR/Resources/SteamVR_Settings.asset file, remember to keep it.

**Comment by chengnay** [comment]
@dpggit For GetStateDown and GetStateUp states, please wait for VIU next release to fix this part.
I found possible root cause that is causing those two functions not working.

**Comment by chengnay** [comment]
@dpggit Please update your VIU from [GitHub](https://github.com/ViveSoftware/ViveInputUtility-Unity), it fixes the GetStateUp and GetStateDown not working issue.

**Comment by qlee01** [comment]
Same issue here, cannot make it work with an already existing project. Tried deleting everything, reinstall SteamVR and HTC.UnityPlugin, but the actions don't work in UGUI demo. UI elements are highlighted, but click events are not registered. In another project it seems to work, both on SteamVR 2.4.5.

**Comment by chengnay** [comment]
@qlee01 Great to hear that, cheers!
