### ISSUE TITLE
Render Model Hook - models for Quest controllers, and index controllers can't be forced

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#158]
if override model is set to Quest or Index, no model shows up.

Unity 2019.2.7f2
VIU 1.10.6.0

**Comment by chengnay** [comment]
@wirelessdreamer Could you double check again for Quest model?
Index controller is missing because there is missing prefab in the controller model folder (Assets\HTC.UnityPlugin\ViveInputUtility\Resources\Models\).
But, Quest model should work fine.

**Comment by wirelessdreamer** [comment]
yes, the model is there.

![image](https://user-images.githubusercontent.com/140221/68977624-a9170a80-07c6-11ea-9768-8f1ca486156f.png)

![image](https://user-images.githubusercontent.com/140221/68977643-b3d19f80-07c6-11ea-8033-eb0baad5924b.png)

![image](https://user-images.githubusercontent.com/140221/68977685-cfd54100-07c6-11ea-9ed1-4305fff89c45.png)

**Comment by chengnay** [comment]
@wirelessdreamer You are missing another model, VIUModelOculusQuestOrRiftSControllerLeft.prefab or VIUModelOculusQuestOrRiftSControllerRight.prefab. Please update from GitHub and try again. Thanks!

**Comment by wirelessdreamer** [comment]
Thanks, that solved it.
