### ISSUE TITLE
Navigation event doesn't  sends if disable laser pointer while pointer above UI element

### ISSUE THREAD

**Issue by Hitomilras** [ViveSoftware/ViveInputUtility-Unity#16]
If laser pointer is above some UI element (and element highlighted), disabling laser pointer doesnt disable ui element highlights.

**Comment by lawwong** [comment]
Hi, thanks for your report.
Handling the hover event when disabling the laser pointer is accidentally skipped by [this line](https://github.com/ViveSoftware/ViveInputUtility-Unity/blob/d42380cb3b58ddf94208ed1b44a89d38f72e47aa/Assets/HTC.UnityPlugin/Pointer3D/Pointer3DInputModule.cs#L234). You can simply remove the line or copy from the [fixed file](https://github.com/ViveSoftware/ViveInputUtility-Unity/blob/261dfbae7df3ed8848d66f7d6ea4c5aed77fa426/Assets/HTC.UnityPlugin/Pointer3D/Pointer3DInputModule.cs) to resolve the bug temporarily. We will release the changes in next version asap.
