### ISSUE TITLE
Controller binding demo doesn't work on quest

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#162]
the default save location on android trys to save the config file in a place that is not allowed on android. android targets (Wave, Quest) need to save the controller binding config in an appropriate place.

**Comment by chengnay** [comment]
@wirelessdreamer What should I do to reproduce your issue?
I am not sure how to save the controller binding config on Android device.

**Comment by wirelessdreamer** [comment]
set the target platform to android, build and push to a device. watch the logs in logcat. make sure you have 2 controllers active. assign a role to one of them and when you hit save, you'll see an error in log cat that the default location it try's to save the config to isn't accessable on android. 

The solution is to save to https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html for android instead.

**Comment by chengnay** [comment]
@wirelessdreamer After you save the file, does it load successfully on start?
VIU's binding does not support Android, that's why we did not allow developer to check "Load Binding Config on Start".
If you tested and it works, I will fix the bug.

**Comment by wirelessdreamer** [comment]
It doesn't save at all, because android doesn't have write permission to the location it try's to save to.

**Comment by chengnay** [comment]
> It doesn't save at all, because android doesn't have write permission to the location it try's to save to.

I mean using your method, it will save to that persistent data path.
Try to modify your cs file,
Assets/HTC.UnityPlugin/ViveInputUtility/Scripts/ViveRole/BindingInterface/BindingInterfaceConfigPanelController.cs,
public void SaveConfig()
{
    ViveRoleBindingsHelper.LoadBindingConfigFromRoleMap();
#if UNITY_ANDROID
    ViveRoleBindingsHelper.SaveBindingConfigToFile(Application.persistentDataPath + "/" + VIUSettings.bindingConfigFilePath);
#else
    ViveRoleBindingsHelper.SaveBindingConfigToFile(VIUSettings.bindingConfigFilePath);
#endif

    m_dirtySymble.SetActive(false);
}

**Comment by wirelessdreamer** [comment]
I made the suggested modifications, and no errors are thrown when save is clicked, but the next the the test app gets loaded, the saved bindings don't get loaded either.

**Comment by chengnay** [comment]
@wirelessdreamer By editing the same script, but under ReloadConfig function.
#if UNITY_ANDROID
            ViveRoleBindingsHelper.LoadBindingConfigFromFile(Application.persistentDataPath + "/" + VIUSettings.bindingConfigFilePath);
#else
             ViveRoleBindingsHelper.LoadBindingConfigFromFile(VIUSettings.bindingConfigFilePath);
#endif

I forgot whether the config file will load automatically or not, but if you click on Reload button, it will reload your saved config file.

**Comment by wirelessdreamer** [comment]
with the above changes, the config never gets loaded. the reload buttons works to load the saved config. I tried the below, and a version where i removed the check for autoLoadBindingConfigOnStart, to always run it, and neither of them loaded the config.

I updated TryInitializeOnLoad to this:

        private static void TryInitializeOnLoad()
        {
            if (VIUSettings.autoLoadBindingConfigOnStart)
            {
#if UNITY_ANDROID
    if(LoadBindingConfigFromFile(Application.persistentDataPath + "/" + VIUSettings.bindingConfigFilePath)) {
        var appliedCount = ApplyBindingConfigToRoleMap();                
        Debug.Log("android ViveRoleBindingsHelper: " + appliedCount + " bindings applied from " + Application.persistentDataPath + "/" + VIUSettings.bindingConfigFilePath);
    }
#else
if (LoadBindingConfigFromFile(VIUSettings.bindingConfigFilePath)){
    var appliedCount = ApplyBindingConfigToRoleMap();
    Debug.Log("ViveRoleBindingsHelper: " + appliedCount + " bindings applied from " + VIUSettings.bindingConfigFilePath);
}
#endif
            }

            if (!Active && VIUSettings.enableBindingInterfaceSwitch)
            {
                Initialize();
            }
        }

**Comment by wirelessdreamer** [comment]
Ignore that last one. the push didn't make it onto the device. Your suggested solution resolved all the issues. feel free to close this once they're in trunk :)
