### ISSUE TITLE
Oculus Quest Problem

### ISSUE THREAD

**Issue by 1027818327** [ViveSoftware/ViveInputUtility-Unity#163]
The oculus quest controller model displays a white model

**Comment by chengnay** [comment]
@1027818327 We are currently working on this part to align with Oculus SDK.
NOTE: You could modify the texture of the controller

**Comment by chengnay** [comment]
@1027818327 Latest VIU v1.11.0 already fixed your issue. Please try it out.
You can get the latest code from GitHub or Unity Asset Store (waiting for Unity to review and publish)
