### ISSUE TITLE
How to get play space boundry data from unity

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#166]
How do we get play space 3d location data with VIU?  Can an example scene be added to the project.

**Comment by chengnay** [comment]
Are you referring to getting chaperone data?

**Comment by wirelessdreamer** [comment]
yes

**Comment by chengnay** [comment]
For OpenVR, there is API for chaperone, but I am not sure about WaveVR and OculusVR.
I might need to check them out in order to add API in VIU and example scene.

**Comment by dariol** [comment]
Here's the official Unity way:
bool UnityEngine.XR.XRInputSubsystem.TryGetBoundaryPoints(Vector3[])

For Wave, this doesn't apply as the system doesn't store chaperone boundaries. Application would need to determine floor via user interaction and the playspace always starts with user in the center and the boundaries defined as 2m x 2m (will have more size options in future Wave updates)
