### ISSUE TITLE
Vive Focus Plus - error in any demo - Unity

### ISSUE THREAD

**Issue by alamboley** [ViveSoftware/ViveInputUtility-Unity#169]
I use Wave SDK 3.1.6 and Unity 2019.2.21f1.

When running any samples, I've this error (I grab it from the Unity console with remote on):
```
[Error] <i>AndroidPlayer(HTC_Vive_Focus_Plus@192.168.1.34)</i> NullReferenceException: Object reference not set to an instance of an object
  at WaveVR_ButtonList.ToEButtons (System.Collections.Generic.List`1[T] eList) [0x00033] in /Users/aymeric/Documents/Workspace/Unity/2020/Enedis-VR-Attention-Marche/Assets/WaveVR/Scripts/WaveVR_ButtonList.cs:47 
  at WaveVR_ButtonList.createHmdRequestAttributes () [0x0000d] in /Users/aymeric/Documents/Workspace/Unity/2020/Enedis-VR-Attention-Marche/Assets/WaveVR/Scripts/WaveVR_ButtonList.cs:241 
  at WaveVR_ButtonList.ResetInputRequest (WaveVR_Controller+EDeviceType device) [0x00030] in /Users/aymeric/Documents/Workspace/Unity/2020/Enedis-VR-Attention-Marche/Assets/WaveVR/Scripts/WaveVR_ButtonList.cs:388 
  at WaveVR_ButtonList.ResetAllInputRequest () [0x0000d] in /Users/aymeric/Documents/Workspace/Unity/2020/Enedis-VR-Attention-Marche/Assets/WaveVR/Scripts/WaveVR_ButtonList.cs:433 
  at WaveVR_ButtonList.Start () [0x0000d] in /Users/aymeric/Documents/Workspace/Unity/2020/Enedis-VR-Attention-Marche/Assets/WaveVR/Scripts/WaveVR_ButtonList.cs:120 
 
(Filename: /Users/aymeric/Documents/Workspace/Unity/2020/Enedis-VR-Attention-Marche/Assets/WaveVR/Scripts/WaveVR_ButtonList.cs Line: 47)
```

If I change `for (int i = 0; i < eList.Count; i++)` to `for (int i = 0; i < eList?.Count; i++)` no more error, but I can't teleport for example anymore.

**Comment by chengnay** [comment]
@alamboley May I know which sample scene you are referring to? Wave SDK or VIU?

**Comment by alamboley** [comment]
Hi @chengnay thanks for the update. It's VIU samples scenes. Having Development Build and  Script Debugging ticked on, give me this error.

**Comment by chengnay** [comment]
I just ticked both, and Teleport scene still works fine.
What else did I miss?

**Comment by chengnay** [comment]
What else you have imported for your project?
VIU (latest version?)? Wave SDK?

**Comment by alamboley** [comment]
Yes I use Wave SDK 3.1.6 and latest VIU release.

The scenes work fine: I can trigger / drag and drop / teleport, but they trigger this serror.

**Comment by chengnay** [comment]
How can I do "I grab it from the Unity console with remote on"??

**Comment by alamboley** [comment]
Does this help? I added Full Log (Developer Mode Only) in the option
<img width="2048" alt="Capture d’écran 2020-03-25 à 11 07 46" src="https://user-images.githubusercontent.com/687978/77525198-ed0ed000-6e88-11ea-8697-bec381fd04a8.png">

**Comment by chengnay** [comment]
Could I clarify the reproduce steps,
1. Build apk with Development Build and Script Debugging ticked
2. Play apk on Focus plus
3. Play scene on Unity Editor
4. Error log will appear?

In step 3, will Unity ask for Android device?
I tested on Windows 10 PC, I couldn't connect with Focus plus.

**Comment by alamboley** [comment]
1. Be sure Unity console is connected to HTC Vive Focus, you can change the target.
2. Build **and run** apk with Development Build and Script Debugging ticked.
3. After scene launch on focus and a basic interaction with the scene, remove the headset and check Unity console, you should have the error.

Notice that you don't need at all to play scene in Unity Editor, it may just remove any previous log.

**Comment by chengnay** [comment]
@alamboley After cowork with WaveSDK RD, I will give you a temporary fix.
In WaveVR_ButtonList.cs,
line 83,
public List<EHmdButtons> HmdButtons = new List<EHmdButtons>();
line 88,
public List<EControllerButtons> DominantButtons = new List<EControllerButtons>();
line 93,
public List<EControllerButtons> NonDominantButtons = new List<EControllerButtons>();

Let me know if you still have issue, thanks!

**Comment by alamboley** [comment]
Thanks @chengnay for the code update. Now I don't have any errors but unfortunately teleport / trigger don't work anymore. Also I can't see when something is pressed/touched on the virtual controller.

**Comment by chengnay** [comment]
I will check with WaveSDK RD and get back to you ASAP.

**Comment by chengnay** [comment]
@alamboley Could you try not to use Unity remote?
WaveSDK RD will need more time to find the root cause.

**Comment by alamboley** [comment]
Hi @chengnay I don't use Unity remote : it's just the Unity console which is in remote mode.

If I comment those lines, I've the same problem than previously: Now I don't have any errors but unfortunately teleport / trigger don't work anymore. Also I can't see when something is pressed/touched on the virtual controller.

**Comment by chengnay** [comment]
It seems your result is different from mine, I can still teleport and trigger. Just I can't see when something is pressed/touched on the virtual controller.

I am still looking into this issue, please be patient, thanks!

**Comment by chengnay** [comment]
@alamboley Here is the solution to your issue.
![image](https://user-images.githubusercontent.com/33050705/77894655-25a71300-72a8-11ea-8fff-e758180557f2.png)

Please also include the solution to WaveVR_ButtonList.cs.
Let me know if you still have issue, thanks!

**Comment by alamboley** [comment]
@chengnay thanks for the update. Could you provide me the code in plain text? Images aren't programmer friendly moreover with the #if statement I don't have any completion.

**Comment by alamboley** [comment]
hi @chengnay I added your fix, no more error and controllers work fine! Thanks :)

**Comment by chengnay** [comment]
> @chengnay thanks for the update. Could you provide me the code in plain text? Images aren't programmer friendly moreover with the #if statement I don't have any completion.

Sorry, because when I paste the code here in plain text, some of the code will not show properly. Such as < WaveVR_ButtonList >.
