### ISSUE TITLE
Anyway to revert ignore all?

### ISSUE THREAD

**Issue by alamboley** [ViveSoftware/ViveInputUtility-Unity#176]
Hello,

For some reason I clicked ignore all, and now it seems I'm not able anymore to accept changes via the default WaveVR_Settings dialog. Anyway to revert it?

**Comment by lawwong** [comment]
Ignored keys are saved in HTC.UnityPlugin\ViveInputUtility\Scripts\Editor\VIUProjectSettings.asset either remove it or clear the list in editor inspector will do.

**Comment by alamboley** [comment]
Got it thanks 👍
