### ISSUE TITLE
TYPO (VIVE Cpsmos) on the Wiki

### ISSUE THREAD

**Issue by segurvita** [ViveSoftware/ViveInputUtility-Unity#177]
I found TYPO on the Wiki.

The Wiki is the following page.
https://github.com/ViveSoftware/ViveInputUtility-Unity/wiki

I'm not sure how to make a pull request to the Wiki, so I'll post it as an Issue.

`Support devices` section says` VIVE Cpsmos` , but it's probably a mistake with `VIVE Cosmos`.

Thank you.

**Comment by chengnay** [comment]
@segurvita Thanks!

**Comment by segurvita** [comment]
Thank you, too.
