### ISSUE TITLE
TYPO (VIVE Focuss+) on the Wiki

### ISSUE THREAD

**Issue by segurvita** [ViveSoftware/ViveInputUtility-Unity#178]
I found another typo on the Wiki.

The Wiki is the following page.
https://github.com/ViveSoftware/ViveInputUtility-Unity/wiki

`Support devices` section says `VIVE Focuss+` , but it's probably a mistake with `VIVE Focus +` or `VIVE Focus Plus`.

Thank you.

**Comment by chengnay** [comment]
@segurvita Done! Thanks!

**Comment by segurvita** [comment]
Thank you too!
