### ISSUE TITLE
Oculus Quest controllers don't support in the Link mode

### ISSUE THREAD

**Issue by ilya-andreyeu** [ViveSoftware/ViveInputUtility-Unity#185]
https://github.com/ViveSoftware/ViveInputUtility-Unity/blob/c26cdf839b379e9536063787d5ccf1a09140edc2/Assets/HTC.UnityPlugin/VRModule/Modules/OculusVRModule.cs#L327

I think, there should be smth like that:

case OVRPlugin.SystemHeadset.Oculus_Quest:
case OVRPlugin.SystemHeadset.Oculus_Link_Quest:
case OVRPlugin.SystemHeadset.Rift_S:

This is works for me.

**Comment by chengnay** [comment]
@ilya-andreyeu Thanks, I will take a look and have this fix in next release.

**Comment by chengnay** [comment]
I tried using Oculus Quest controllers, but I didn't get Oculus_Link_Quest.
I will see Rift_S when I connect through Link.
Could you provide more detailed information?
Such as which Unity version? Oculus Integration? Oculus Desktop package or Unity XR Plugin?

**Comment by ilya-andreyeu** [comment]
I used the latest version of the VIU (not release but develop) at the time of the proposed update and the latest Oculus SDK version (it was the 17.0). Unity version is 2019.2.8f1. Also i used the Oculus Desktop package v.1.38.4.

This version of the Oculus SDK, as i know, don't contains interactable models of Rift S controllers (maybe it was fixed in the 18.0, i was on vacation). When i try to connect to my app with the Oculus Quest Link, it wasn't support at all. I tried to find the reason and found that the Oculus SDK separates the Oculus Quest Link into a separate type. The Quest has same controllers with Rift S.

**Comment by chengnay** [comment]
@ilya-andreyeu I use the same environment settings(Unity 2019.2.8f1, Oculus SDK v17.0 and Oculus Desktop package v1.38.4), I am not able to reproduce the same issue. I will be getting Rift_S instead.
![image](https://user-images.githubusercontent.com/33050705/88154233-140fbf80-cc39-11ea-8d3e-faa1e7df66bd.png)
![image](https://user-images.githubusercontent.com/33050705/88154020-cabf7000-cc38-11ea-9356-26f495a4d24b.png)

I will still add your fix to next VIU release. :)

**Comment by ilya-andreyeu** [comment]
You are using the Rift S, as i can see. I'm used the Oculus Quest with Link (you said that you haven't got it).

At all, i'm glad to see that VIU release a new versions and i'm already use it in our new application. Thanks for your job!)

**Comment by chengnay** [comment]
@ilya-andreyeu Of cause I am using Oculus Quest, but that's what I get from Oculus SDK.
Maybe I did plug in Oculus Rift S before, so it will give me that device name instead?
![image](https://user-images.githubusercontent.com/33050705/88364670-34b15400-cdb6-11ea-9d46-c08c95b33311.png)

Anyway, if you still have issues, feel free to ask in GitHub or [VIVE forum](https://forum.vive.com/forum/72-vive-input-utility/?ct=1564382437).

**Comment by chengnay** [comment]
@ilya-andreyeu Please test with the [latest VIU v1.12.0](https://github.com/ViveSoftware/ViveInputUtility-Unity/releases/latest), thanks!

**Comment by ilya-andreyeu** [comment]
@chengnay in the v1.12.0 it works fine. Thanks! <3
