### ISSUE TITLE
Lag when playing a Scene

### ISSUE THREAD

**Issue by valdeezzee** [ViveSoftware/ViveInputUtility-Unity#186]
I am running Unity 2019.4.2. I have steamvr and Vive Input Utility installed. When I play a scene, the editor freezes for about 10 seconds before I can do anything. The whole editor freezes and I can't click on any other windows in the editor. I've tried running an empty scene and I get the same results. I have also tried running this same scenario as above in 2018.3.9 and no luck. If I removed ViveInput, everything works as expected and there is no lag.

The same issue happens in a build but the lag is only a few seconds.

**Comment by NagaChiang** [comment]
We've looked into the issue. It takes too long to update the define symbols. This will be optimized in the next release.

Thanks for reporting!

**Comment by lawwong** [comment]
[VRModuleManagerEditor.zip](https://github.com/ViveSoftware/ViveInputUtility-Unity/files/4971292/VRModuleManagerEditor.zip)
This patch should fixes the issue, let us know if it works, thanks.

**Comment by valdeezzee** [comment]
I added it and it gave me this error: 'VIUSettingsEditor' does not contain a definition for 'VIUPackageName'
The error happen in VRModuleManagerEditor.cs on line 325.

**Comment by ilya-andreyeu** [comment]
Hi. We have the same problem. It was the editor's scripts. We are deleted a lot of them and fix this trouble. But we have another - we are removing a lot of editor's scripts))

@NagaChiang [https://drive.google.com/file/d/13vRIkUGEV0rzvNxJ60bX5xb4coV8yJbz/view?usp=sharing](link to the removed files)

**Comment by lawwong** [comment]
Oops, my bad.
I created new hotfix branch, plz refer to the new link, thanks.
[fixed file link](https://github.com/ViveSoftware/ViveInputUtility-Unity/blob/v1.11.0-hotfix/Assets/HTC.UnityPlugin/VRModule/Editor/VRModuleManagerEditor.cs)
[fixed file raw](https://raw.githubusercontent.com/ViveSoftware/ViveInputUtility-Unity/v1.11.0-hotfix/Assets/HTC.UnityPlugin/VRModule/Editor/VRModuleManagerEditor.cs)

**Comment by lawwong** [comment]
Fixed in v1.12.0
