### ISSUE TITLE
Common button features missing for ViveController

### ISSUE THREAD

**Issue by dim8** [ViveSoftware/ViveInputUtility-Unity#189]
Any button-related common features e. g. `CommonUsages.menuButton` are missing and only default values are returned instead. This results in no controller interaction. The full list of present features and their value types is then the following:

- DevicePosition (UnityEngine.Vector3)
- DeviceRotation (UnityEngine.Quaternion)
- DeviceVelocity (UnityEngine.Vector3)
- DeviceAngularVelocity (UnityEngine.Vector3)
- TrackingState (System.UInt32)
- IsTracked (System.Boolean)

This behaviour also occurs with any of the example scenes. For instance, in the _UGUI.scene_ both controllers are rendered and tracked correctly, the pointer is also there, but any of the GUI elements cannot be interacted with.

In the console the following warning messages can be read:

> Device OpenVR Controller(Vive Controller MV) - Right doesn't have bool feature MenuButton. Return default value instead.
> Device OpenVR Controller(Vive Controller MV) - Right doesn't have bool feature Primary2DAxisClick. Return default value instead.
> Device OpenVR Controller(Vive Controller MV) - Right doesn't have bool feature TriggerButton. Return default value instead.
> Device OpenVR Controller(Vive Controller MV) - Right doesn't have bool feature Primary2DAxisTouch. Return default value instead.
> Device OpenVR Controller(Vive Controller MV) - Right doesn't have bool feature GripButton. Return default value instead.
> Device OpenVR Controller(Vive Controller MV) - Right doesn't have float feature Trigger. Return default value instead.
> Device OpenVR Controller(Vive Controller MV) - Right doesn't have Vector2 feature Primary2DAxis. Return default value instead.
> 
> Device OpenVR Controller(Vive Controller MV) - Left doesn't have bool feature MenuButton. Return default value instead.
> Device OpenVR Controller(Vive Controller MV) - Left doesn't have bool feature Primary2DAxisClick. Return default value instead.
> Device OpenVR Controller(Vive Controller MV) - Left doesn't have bool feature TriggerButton. Return default value instead.
> Device OpenVR Controller(Vive Controller MV) - Left doesn't have bool feature Primary2DAxisTouch. Return default value instead.
> Device OpenVR Controller(Vive Controller MV) - Left doesn't have bool feature GripButton. Return default value instead.
> Device OpenVR Controller(Vive Controller MV) - Left doesn't have float feature Trigger. Return default value instead.
> Device OpenVR Controller(Vive Controller MV) - Left doesn't have Vector2 feature Primary2DAxis. Return default value instead.

Based on the severity of the resulting behaviour (no controller events), change from warning to error may be suitable.

Also, for the same version I had problems installing the OpenVR XR Plugin, because the package had been renamed from `com.valve.openvr` to `com.valvesoftware.unity.openvr`. The plugin being out of preview fairly recently explains that.

**Unity version: Unity 2020.1.1f1**
**ViveInputUtility version: Vive Input Utility v1.11.0**

**Comment by chengnay** [comment]
@dim8 Could you try to update VIU to latest version (v1.12.0)?

**Comment by dim8** [comment]
I updated VIU to v1.12.0 and also tested it on a new empty project. The issue still persists, and I did the following:

1. Create new empty Unity project (3D Template) with Unity 2020.1.1f1.
2. Open the [Unity package of VIU v1.12.0](https://github.com/ViveSoftware/ViveInputUtility-Unity/releases/download/v1.12.0/ViveInputUtility_v1.12.0.unitypackage) and import it in the project.
3. Unload the sample scene and add the UGUI scene. Start the player.
4. Try to click on any of GUI elements.

My setup is a Vive Pro with standard Vive Controllers on 64-bit Windows. Also using the Vive wireless adapter, if this is of importance.

**Comment by chengnay** [comment]
@dim8 You checked the OpenVR in VIU Settings?
But, did you import SteamVR Unity Plugin too?

**Comment by dim8** [comment]
Yes, sure I just forgot to include it in the steps above. 

SteamVR, on the other hand, was not imported, but before updating to Unity 2020.1.1f1, i.e. with Unity 2018 LTS, this was not necessary. May SteamVR be required for VIU on 2020.1.1f1?

**Comment by chengnay** [comment]
In the latest OpenVR XR Plugin (preview4 and above), you need SteamVR Unity Plugin (>v2.6.0) to get input events.

**Comment by dim8** [comment]
Great, that solved the issue!

I also needed to add the correct controller bindings for my Unity project. Though, for the empty test project with VIU it worked out of the box.
