### ISSUE TITLE
How to read Velocity and Angular Velocity from devices

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#19]
I didn't see anything in the examples about how to read velocity or angular velocity of devices.

**Comment by wirelessdreamer** [comment]
I've tried using
SteamVR_TrackedObject trackedObj;
trackedObj = gameObject.GetComponent<SteamVR_TrackedObject>();
viveRole = ViveRoleProperty.New(gameObject.transform.parent.GetComponent<ViveRoleSetter>().viveRole);
trackedObj.SetDeviceIndex((int)viveRole.GetDeviceIndex());

and then pulling velocity off of the tracked object, but the index's don't appear to match up.

**Comment by dariol** [comment]
Hi wirelessdreamer,

Basically VIU replaces the need to use SteamVR_TrackedObject. See the ViveCameraRig or ViveRig prefabs for reference. Also take a look at the guide pdf for details. Basically VivePoseTracker replaces SteamVR_TrackedObject using a role instead of an index. A benefit of using roles allows one to persist devices so that bindings can be re-established across starts easily.

**Comment by wirelessdreamer** [comment]
I don't see a replacement method to get velocity in VIU, the only reason I tried the above was trying to find ways to get angular and rotational velocity. what is the method to get it with VUI?

**Comment by lawwong** [comment]
In short cut:
``` csharp
using UnityEngine;
using HTC.UnityPlugin.Vive;

public class GetDeviceVelocity : MonoBehaviour
{
    public ViveRoleProperty role = ViveRoleProperty.New(HandRole.RightHand);
    public Vector3 velocity;
    public Vector3 ancularVelocity;

    private void Update()
    {
        velocity = VivePose.GetVelocity(role);
        ancularVelocity = VivePose.GetAngularVelocity(role);
    }
}
```

If you need more detail, you can get them from the device state, which returned from VRModule.GetCurrentDeviceState under HTC.UnityPlugin.VRModuleManagement. We will add VRModule in the document later.

``` csharp
using UnityEngine;
using HTC.UnityPlugin.Vive;
using HTC.UnityPlugin.VRModuleManagement;

public class PrintDeviceState : MonoBehaviour
{
    public ViveRoleProperty role = ViveRoleProperty.New(HandRole.RightHand);

    private void Update()
    {
        IVRModuleDeviceState deviceState = VRModule.GetCurrentDeviceState(role.GetDeviceIndex());
        Debug.Log("velocity=" + deviceState.velocity);
        Debug.Log("angularVelocity=" + deviceState.angularVelocity);
        Debug.Log("serialNumber=" + deviceState.serialNumber);
        Debug.Log("modelNumber=" + deviceState.modelNumber);
        Debug.Log("deviceClass=" + deviceState.deviceClass);
    }
}
```

**Comment by wirelessdreamer** [comment]
Thank you, thats what I was looking for.
