### ISSUE TITLE
Controller doesn't work on Oculus Quest

### ISSUE THREAD

**Issue by tenebris93** [ViveSoftware/ViveInputUtility-Unity#198]
### Description
The controller works in the tutorial scene on Vive Focus Plus but not on the Oculus Quest.

### Build Environment
I created a fresh test project using VIU (v1.12.0.0) in Unity (v2019.4.11 LTS).
The only packages added were the XR packages for WaveVR (v1.0.1) and Oculus (v1.4.3).
The only settings tweaked were the recommended project settings provided by VIU for each headset.
During testing, I was only using the right controller. The left controller had its battery removed.

### Notes
Not sure if there is anything else I'm supposed to do to get VIU to work on Oculus.
Afterward, I tried to add Oculus's Integration plugin from the asset store to the project. Thinking it might be a prerequisite to get it to work, but instead, it would cause Unity to crash to desktop. Not exactly sure why it was doing that.

**Comment by chengnay** [comment]
@tenebris93 I cannot reproduce the issue.

![image](https://user-images.githubusercontent.com/33050705/95731322-f3905800-0cb1-11eb-9b5a-37af09668638.png)
Did you check both WaveVR and Oculus Android?

**Comment by tenebris93** [comment]
The scene I was having issues with was the Tutorial sample scene.

Seeing I wasn't able to figure out what was causing the issue. I have since started using the camera rigs that the WaveXR SDK and Oculus provides. I just disable whichever one I'm not in need of.
