### ISSUE TITLE
X or A key press not working in Vive Cosmos

### ISSUE THREAD

**Issue by SoumyaBasheer** [ViveSoftware/ViveInputUtility-Unity#204]
I used ViveInput.GetPressDown(HandRole.LeftHand, ControllerButton.AKeyTouch) for getting X button press in left hand and  ViveInput.GetPressDown(HandRole.RightHand, ControllerButton.AKeyTouch) for getting A button press in right hand , but its not working in vive cosmos

**Comment by chengnay** [comment]
@SoumyaBasheer Could you list the Unity Editor, VIU and SDK version?

**Comment by SoumyaBasheer** [comment]
Hi
While testing through  SteamVR Controller Settings>Test Controller I could see the Touch of X and A buttons.

![XButton](https://user-images.githubusercontent.com/25294963/96998356-f3fdde00-1550-11eb-929d-cce7d412d86c.png)

I used ViveInputUtility from assetstore (https://assetstore.unity.com/packages/tools/integration/vive-input-utility-64219)
Unity Version - 2019.4.2
VIU Version - 1.12.0.0

**Comment by chengnay** [comment]
Are you testing this in VIU’s example scene?

**Comment by SoumyaBasheer** [comment]
@chengnay I checked this but I am not getting Akey. but Bkey is working perfectly. Whether I miss anything?

**Comment by chengnay** [comment]
Could you provide a sample project that can reproduce this issue for debugging?

**Comment by SoumyaBasheer** [comment]
@chengnay I have uploaded a sample in the link https://drive.google.com/file/d/1J3uib08xXSGoMsetuUpLrn1O7ga6ErNb/view?usp=sharing. Can test it using Test Scene and put a Error log in TestScript for A and B key press.

**Comment by chengnay** [comment]
It seems like you did not use SteamVR Unity Plugin, only install OpenVR Desktop plugin from Unity Package Manager.

Here is the fix to your issue.

In Assets\HTC.UnityPlugin\VRModule\Modules\UnityEngineVRModule.cs,
For function Update_L_Vive,
Add below lines,
var primaryButtonPress = GetUnityButton(3);
currState.SetButtonPress(VRModuleRawButton.A, primaryButtonPress);

Do the same for Update_R_Vive,
var primaryButtonPress = GetUnityButton(1);
currState.SetButtonPress(VRModuleRawButton.A, primaryButtonPress);

Sorry for the inconvenience!

**Comment by SoumyaBasheer** [comment]
@chengnay  Thank you It worked for me. Do I need to use SteamVR Unity Plugin. I just wanted some interaction and teleporting I hope it can acheive using OpenVR  and VIU. Please correct me if am wrong

**Comment by chengnay** [comment]
@SoumyaBasheer It is your choice to use SteamVR Unity Plugin or not.
If you would like to use trackers, then you MUST import SteamVR Unity Plugin.
As for interaction and teleport, OpenVR and VIU will be enough for now.
You can always expand your project with SDKs(such as SteamVR Unity Plugin), VIU will take care of everything.

**Comment by SoumyaBasheer** [comment]
@chengnay Thank you for the update. I hope this issue will fix in Next version. Thank you so much for the quick response.

**Comment by chengnay** [comment]
@SoumyaBasheer Yes, this fix will be included in the next release. Thanks for your support. :)
