### ISSUE TITLE
Screen position out of view frustum 

### ISSUE THREAD

**Issue by Rorschach1219** [ViveSoftware/ViveInputUtility-Unity#205]
![图片](https://user-images.githubusercontent.com/20067002/96864319-cce4d500-149a-11eb-956b-7aa4c96df897.png)

I ran the sample scenario separately, and there was no such error report. When I installed vrorigin into my main scenario, this error was reported. Although there was no effect, I wanted to know how to make it not report errors

**Comment by chengnay** [comment]
@Rorschach1219 Could you try the methods in this [link](https://forum.unity.com/threads/screen-position-out-of-view-frustum.9918/)?

**Comment by Rorschach1219** [comment]
I've tried them. They don't work

**Comment by chengnay** [comment]
Could you provide a sample project that can reproduce this error? Since you mentioned that VIU’s example scene will not show that error.

**Comment by Rorschach1219** [comment]
> 
> 
> Could you provide a sample project that can reproduce this error? Since you mentioned that VIU’s example scene will not show that error.

https://drive.google.com/file/d/1u5c6bq5d-FuZUPa1mMYj_pQLrbpwnoZ5/view?usp=sharing

Please see the demo in this video

**Comment by chengnay** [comment]
@Rorschach1219 After following your demo video, I could not reproduce the issue.
![image](https://user-images.githubusercontent.com/33050705/97824050-d6213d80-1cf5-11eb-9e47-4687f7ab15d0.png)
My Field of View will not change after playing in Unity Editor.
![image](https://user-images.githubusercontent.com/33050705/97824108-049f1880-1cf6-11eb-89d9-586f911fefb7.png)
After adding ViveCameraRig, there is no error too.

By the way, it seems before you added ViveCameraRig to JPickup Demo scene, the error message is already existed. Did you make any modification?
Could you try creating a new project?

**Comment by Rorschach1219** [comment]
Sorry for the late reply, I will try it today.

ChengNan Yang <notifications@github.com> 于2020年11月2日周一 上午10:29写道：

**Comment by Rorschach1219** [comment]
VPP alone will not have this problem. I think the VR suite has affected it

**Comment by Rorschach1219** [comment]
@chengnay  My computer is very strange, you did not reproduce this problem, I don't know what to do

**Comment by Rorschach1219** [comment]
@chengnay  I have a question. Can VIU run independently? HTC view device? I imported steamvr. I don't know if it is necessary

In a new project, after importing VPP and running demo scene, the FOV of camera will be changed externally. Screen position out of view frustum (screen POS 0.000000, 0.000000, 1000.000000) (camera rect 0.0 1424 1680)
UnityEngine.GUIUtility :ProcessEvent(Int32, IntPtr)

![图片](https://user-images.githubusercontent.com/20067002/99145201-c582a700-26a7-11eb-8da9-1763fa26c17d.png)

**Comment by Rorschach1219** [comment]
@chengnay  I have tried it. If a pure new project only imports VIU without any settings and import steam, then VR cannot run normally, and VPP can also run normally, no error is reported, and FOV has not changed, but what I want is , In the normal mode of VR, the camera will not change for no reason and will not report an error
