### ISSUE TITLE
Unity DirectPreview Streaming Server error

### ISSUE THREAD

**Issue by xkyl-yhw** [ViveSoftware/ViveInputUtility-Unity#211]
After click the "start Streaming Server", It shows and close down. If it is still exist, the Focus will not show "Connection timeout". But I got not idea how to do so. I use the cmd to open the SServer.

C:\Windows\system32>E:\unity\2019Training\OpencvSDKExercise\Assets\WaveVR\Platform\Windows\dpServer.exe
The server config:.\config\serverSetting.setting loaded fail!
The HmdList is not loaded! error:1
OnPipeInfo : Pipe Server Started
Pipe accept begin.
file_num :32
[2021-01-26 21:53:02.860 +8 7800 DEBUG logger] [Main] Set Log level as DEBUG

[2021-01-26 21:53:02.867 +8 7800 INFO logger] [Main]Init() Config from json: H265:false, Bitrate:25000000, GOP:105, EncodeHQ true, AllIFrame false
, ForceToSendTexture false, WaitDecodeDoneTimeOut 15 ms, fps 75,LogToFile:true,RTPPayloadSize:30000

[2021-01-26 21:53:02.870 +8 7800 INFO logger] [Main] GetGpuType() There are 3 adapter

[2021-01-26 21:53:02.870 +8 7800 INFO logger] [Main] GetGpuType() The GPU [0] vendor id is 5140, vendor description is Microsoft Basic Render Driver

[2021-01-26 21:53:02.870 +8 7800 INFO logger] [Main] GetGpuType() The GPU [1] is Nvidia!

[2021-01-26 21:53:02.871 +8 7800 DEBUG logger] OnPipeInfo(): Pipe Server Started

C:\Windows\system32>

Plz help me.

**Comment by chengnay** [comment]
@xkyl-yhw Could you try those steps discuss in this [thread](https://forum.vive.com/topic/8936-direct-preview-in-unity-not-working-help/?ct=1611904572)?
If it still doesn't help, please let me know, thanks!

**Comment by xkyl-yhw** [comment]
@chengnay I have already try those steps, but it doesn’t work. The server still shot down at once. I think maybe is gpu’s issue? My graphics card is MX150.

**Comment by chengnay** [comment]
@xkyl-yhw Please provide the versions(Unity Editor, WaveVR SDK and VIU) that you are using?

**Comment by xkyl-yhw** [comment]
@chengnay unity 2018.4.12f1 SDK3.20

**Comment by chengnay** [comment]
> After click the "start Streaming Server", It shows and close down. If it is still exist, the Focus will not show "Connection timeout". But I got not idea how to do so. I use the cmd to open the SServer.
> 
> C:\Windows\system32>E:\unity\2019Training\OpencvSDKExercise\Assets\WaveVR\Platform\Windows\dpServer.exe
> The server config:.\config\serverSetting.setting loaded fail!
> The HmdList is not loaded! error:1
> OnPipeInfo : Pipe Server Started
> Pipe accept begin.
> file_num :32
> [2021-01-26 21:53:02.860 +8 7800 DEBUG logger] [Main] Set Log level as DEBUG
> 
> [2021-01-26 21:53:02.867 +8 7800 INFO logger] [Main]Init() Config from json: H265:false, Bitrate:25000000, GOP:105, EncodeHQ true, AllIFrame false
> , ForceToSendTexture false, WaitDecodeDoneTimeOut 15 ms, fps 75,LogToFile:true,RTPPayloadSize:30000
> 
> [2021-01-26 21:53:02.870 +8 7800 INFO logger] [Main] GetGpuType() There are 3 adapter
> 
> [2021-01-26 21:53:02.870 +8 7800 INFO logger] [Main] GetGpuType() The GPU [0] vendor id is 5140, vendor description is Microsoft Basic Render Driver
> 
> [2021-01-26 21:53:02.870 +8 7800 INFO logger] [Main] GetGpuType() The GPU [1] is Nvidia!
> 
> [2021-01-26 21:53:02.871 +8 7800 DEBUG logger] OnPipeInfo(): Pipe Server Started
> 
> C:\Windows\system32>
> 
> Plz help me.

Your log stops after Pipe Server Started?

Previously, I will see more logs like below,
[2020-10-15 13:45:09.960 -7 12488 ERROR logger] [Main]Init() Nvidia driver may be too old, please update to the latest version driver and try again.
[2020-10-15 13:45:09.961 -7 12488 ERROR logger] [Main]Init() fail,so break

**Comment by xkyl-yhw** [comment]
@chengnay Yes, it just stop after 3 seconds. 

 [2020-10-15 13:45:09.960 -7 12488 ERROR logger] [Main]Init() Nvidia driver may be too old, please update to the latest version driver and try again.
[2020-10-15 13:45:09.961 -7 12488 ERROR logger] [Main]Init() fail,so break
Those conditions I also have before I disable the gpu of intel(R) UHD Graphics 620, while I learn from the link you give me.
https://forum.vive.com/topic/8936-direct-preview-in-unity-not-working-help/?ct=1611904572

**Comment by xkyl-yhw** [comment]
@chengnay Thanks for your help, despite I didn't work out the direct preview, I used the previous version. And it's works. I use the v3.0.2 and start simulate.
