### ISSUE TITLE
Joystick values always zero on Quest when running thorugh Oculus Link on OpenVR

### ISSUE THREAD

**Issue by Pjchardt** [ViveSoftware/ViveInputUtility-Unity#214]
ViveInput.GetAxis(HandRole.rightHand, ControllerAxis.JoystickX) works as expected on Index and Rift. However, on Quest running on SteamVR through Oculus Link the values are always 0.

**Comment by Pjchardt** [comment]
I looked into a work around solution by checking the deviceModel, but that is returning unknown for Quest controllers.

**Comment by chengnay** [comment]
https://forum.vive.com/topic/9400-joystick-values-always-zero-on-quest-when-running-thorugh-oculus-link-on-openvr/?tab=comments#comment-39671&ct=1615854415
