### ISSUE TITLE
Microsoft Mixed reality headsets stutter painfully when using ViveCameraRig, work fine with SteamVR CameraRig

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#24]
Microsoft Mixed reality headsets stutter painfully when using ViveCameraRig, work fine with SteamVR CameraRig

I currently have to switch the camera i'm using to support mixed reality devices. It would also be nice to be able to select MR devices in the device chooser, Example 7, role binding example.

**Comment by lawwong** [comment]
Ok, thanks for the report, will find it out.

**Comment by wirelessdreamer** [comment]
Thanks, let me know if you want any extra testing from my end.

**Comment by dariol** [comment]
hi wirelessdreamer,

I was not able to reproduce your problem, I tried what you mentioned using all the latest:  plugins, Unity, Windows, SteamVR(beta). There was no difference in performance between CameraRig, ViveCameraRig, or ViveRig. No stutter. I even tried without the SteamVR plugin installed with the same result and even ran without Steam/SteamVR at all by targeting UWP i.e. a native Windows MR app using VIU where even the basic buttons worked so I could grab objects etc. 

The only issue is a missing model for the controllers when the SteamVR plugin is not included. and some missing button mappings when targeting UWP.  You can enable the built in example model when pressing the "grip" button when using ViveRig until we add detecting Windows MR headsets to enable a  controller model or you can hard code enabling the Vive controller models provided.

Please provide additional detailed info or screen grabs if the stutter is still happening.

-Dario

**Comment by wirelessdreamer** [comment]
I've only seen this issue in one project, changing over to this plugin from VRTK for another project resolved performance issues the other project was seeing. I believe I saw the issue because of lighting performance issues in the project I opened this issue on.
