### ISSUE TITLE
Is it possible to get range value of trigger input from vive tracker?

### ISSUE THREAD

**Issue by Thaina** [ViveSoftware/ViveInputUtility-Unity#249]
As the vive controller have trigger button that can report range of value. But it seem vive tracker (the small tripod) which contains 6 pins can only report 0 or 1

Is this the limit of the tracker hardware or we could actually control voltage/amp to output trigger range value too?

**Comment by chengnay** [comment]
Hi @Thaina,
How did you get the trigger button input?
Could you paste your sample code?

**Comment by Thaina** [comment]
By custom hardware

![image](https://user-images.githubusercontent.com/1042507/230342549-f548cb40-40ad-4d81-98fa-1393512ff7fe.png)

**Comment by chengnay** [comment]
Hi @Thaina,
By using custom hardware(POGO pin), you can only get 0 or 1 for trigger button.
You need to send trigger event by USB interface to Vive Tracker in order to report range of values.

**Comment by Thaina** [comment]
I see, Thank you very much
