### ISSUE TITLE
Controller models no showing up in Simulator

### ISSUE THREAD

**Issue by MBrill** [ViveSoftware/ViveInputUtility-Unity#253]
We use Unity 2023.3.23f1 LTS, VIU 1.18.

Running our projects and the example scenes with Vive Pro or Focus work just fine. 

In a project where we only use the simulator we do not see any models of controllers. Not in our projects, not in the example scenes.We see the rays for ray casting, controllers are moved with WASD - but we do not see them in the simulator. We experimented a lot with Render Model Hook or custom models in the settings without a result.

Any ideas?

**Comment by MBrill** [comment]
Found a solution :-), maybe.

We checked one of the examples, 7.RoleBindingExample. There controllers are shown in simulator. The Reason seems to be, under VROrigin there is a gameobject "Models". checking on nr. 1 or nr. 2, the controllers, for *Vive RoleSetter *you find *Device Role* with the correct index.

Tried that on an empty project, imported VIU 1.18.1, use ViveCameraRig and use either the correct DeviceRole or the correct ControllerRole in the ViveRoleSetter component of the LeftHand and RightHand objects in the rig.

We still have to check if the application runs with the HMD. And we just checked: using VIU 1.15, everything worked without changing the component *ViveRoleSetter*.

**Comment by chengnay** [comment]
Hi @MBrill,
I will double check on my side and get back to you ASAP. :)

**Comment by chengnay** [comment]
Hi @MBrill,
Thanks for pointing out this bug which existed since v1.16.
Below is the patch to this issue and we will update in next version.
![image](https://github.com/ViveSoftware/ViveInputUtility-Unity/assets/33050705/2f5f74ad-bc62-4e72-8d32-1c24037f2eca)

**Comment by lawwong** [comment]
Added fix in 87340ea2

**Comment by MBrill** [comment]
Great, thanks a lot!

Yes, sorry, 2023 was a typo :-) We use the latest 2021 LTS.

**Comment by MBrill** [comment]
Again thanks!
