### ISSUE TITLE
Clickable widgets in ScrollRect

### ISSUE THREAD

**Issue by fishsama** [ViveSoftware/ViveInputUtility-Unity#26]
Version of Unity3D : 5.5.2f1
Version of ViveInputUtility : 1.7.3

Question : 
I want to make a button list so I created some buttons in scrollrect, when the raycast points to the button and I try to drag the list, it can not work correctly.

**Comment by lawwong** [comment]
Sorry for the delay.
Can you provide your steps to reproduce the issue?
And how it doesn't work correctly? Can't receive press event or not slide properly?

**Comment by fishsama** [comment]
I put some buttons in scrollrect, when I tried to drag down the button-list and it showed the actual function was click, but I have updated ViveInputUtility to version 1.8.0 today and the problem has been fixed.
Thanks for reply
