### ISSUE TITLE
Switch left / right Eye as Display Monitor

### ISSUE THREAD

**Issue by benjaminshp** [ViveSoftware/ViveInputUtility-Unity#27]
Version of Unity3D : 2017.3.0f3
Version of ViveInputUtility : 1.7.3

Question :
Is it possible to mirror the right eye of the HMD to the Monitor.. ?
At the moment its the left... for shooters using the right eye for aiming, 
it would be more impressive...
and my client requested it ;-)

thank you in advance

benjamin

**Comment by wirelessdreamer** [comment]
I've been looking for a performant way to handle this as well. I'm pretty sure its just a unity issue, and has nothing to do with this package, as in the editor you can select the eye to display, but if you try to handle it by creating another camera, and targeting main display its a major hit.

**Comment by wirelessdreamer** [comment]
Awesome, i missed that update. @benjaminshp this should be all you were looking for, good to close it?

**Comment by wirelessdreamer** [comment]
@dariol I may of jumped the gun, when I went to implement that, all it looks like it is doing is changing target eye on the camera from both, to the eye that is specified. What @benjaminshp and I were looking for is to set this property from the default of left, to right:
![image](https://user-images.githubusercontent.com/140221/44760415-af12c400-ab0c-11e8-9b32-b0e63489d1d5.png)

**Comment by bddckr** [comment]
It's just the wrong API. That one defines what is rendered altogether.

The API to use to change what is viewed in the Game View or in the build's main window is [`XRSettings-gameViewRenderMode`](https://docs.unity3d.com/2018.2/Documentation/ScriptReference/XR.XRSettings-gameViewRenderMode.html).

**Comment by benjaminshp** [comment]
Great .. it works ;-)
  XRSettings.gameViewRenderMode = GameViewRenderMode.RightEye;
