### ISSUE TITLE
HTC Controllers are spawning on 0,0,0 on version 1.8

### ISSUE THREAD

**Issue by sergio-nnz** [ViveSoftware/ViveInputUtility-Unity#28]
I'am using Steam 1.2.3 and Unity 2017.1
The issue is every time I start the scene the controllers spawn on the scene origin.
![before](https://user-images.githubusercontent.com/17553732/36221132-fb6c2d44-1171-11e8-8dab-30201ac58d22.PNG)
Only when I press the system button, go to the steam dashboard and go then press the system button again to back to my scene the trackers work again.
![after](https://user-images.githubusercontent.com/17553732/36221116-eefdaf10-1171-11e8-9772-f9ed17386357.PNG)

**Comment by sergio-nnz** [comment]
Don't if it helps but VRModule.HasInputFocus() also initializes as false.

**Comment by dariol** [comment]
Hi, please try again with the very latest SteamVR runtime (from 2 days ago) - I was not able to repro with Unity 2017.3 and  2018.1beta

**Comment by CriticalMammal** [comment]
I seem to be running into the same exact issue. I'm updated to the latest SteamVR update (Feb 13th) and running on Unity 2017.3.1. I think this may actually be an issue with the SteamVR update itself though. There are others who were having issues with controllers suddenly not tracking with the newer update, and the suggested temporary solution is using the "openvr-inputemulator-temporary" beta branch of steamVR. This didn't solve it for me though. Actually it made it worse, the controllers don't appear at all and the steam dashboard trick to get them tracking again doesn't work on that branch.

**Comment by JeffBail** [comment]
I'm having the same issue with Unity 2017.3.0f3 and SteamVR 1518226924. Jumping into the SteamVR menu and then back out again seems to fix it and the controller models begin tracking. Please note that the date isn't a great way to identify your Steam VR version as the official announcement (http://store.steampowered.com/news/externalpost/steam_community_announcements/2363697377468531896) is dated 2/13 and the Help, About box in Steam VR shows 2/9.

**Comment by lawwong** [comment]
#29 
Sorry guys, it was a typo.
060892490f18f041c24896edc617bceeeb3fa37a
Please apply the change, should fix it
