### ISSUE TITLE
How to use simulator?

### ISSUE THREAD

**Issue by Hitomilras** [ViveSoftware/ViveInputUtility-Unity#30]
I think that this asset is a little bit outdocumented... Really..
You added simulator, but how to use it? Any examples? Nothing :(

help please...

**Comment by lawwong** [comment]
The control key mapping at the last section of the [release not](https://github.com/ViveSoftware/ViveInputUtility-Unity/releases/tag/v1.8.0), its not in the document yet, sorry about that.

Basically you use ASDW to move around HMD or devices, and move your mouse to change their orientation.
But you can only control one device at a time.
To switch controlling device, press keyboard number keys [0~9] to do so.
  - [0] is HMD
  - [1~2] are VIVE Controllers
  - [3~9] are VIVE Trackers

Will write more if you need further help :)

**Comment by wirelessdreamer** [comment]
How do you disable the simulator, when I'm running builds and steamvr isn't active, its starting the game up with the simulator active, which is undesirable.

**Comment by lawwong** [comment]
@wirelessdreamer 
You have to disable it in settings window.
![VIUSettings](https://github.com/ViveSoftware/ViveInputUtility-Unity/raw/gh-pages/assets/img/viusettings_preview_01.png)

**Comment by lawwong** [comment]
f976f9d08499a340ddbba3f4b3d72fc704775975
This commit fix a possible bug that causes project doesn't save the setting changes.
You may have to edit VIUSettings.asset manually or update to v1.8.0.4 before we release v1.8.1 asap.

**Comment by wirelessdreamer** [comment]
Thanks.

**Comment by lawwong** [comment]
https://github.com/ViveSoftware/ViveInputUtility-Unity/wiki/Simulator
