### ISSUE TITLE
Version 1.8.1 Controllers dissapearing

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#35]
I've seen multiple times while testing release 1.8.1 my controllers disappear, every time it happens this is the error spamming the console.

NullReferenceException: Object reference not set to an instance of an object
HTC.UnityPlugin.VRModuleManagement.VRModule.GetShouldActivateModule () (at Assets/HTC.UnityPlugin/VRModule/VRModuleManager.cs:144)
HTC.UnityPlugin.VRModuleManagement.VRModule.Update () (at Assets/HTC.UnityPlugin/VRModule/VRModuleManager.cs:95)

I upgraded to 1.8.0 from the previous version 1st by deleting the HTC.UnityPlugin folder, 
I was not able to reproduce this error with 1.8.0. on 1.8.0 my controllers initially didn't show up till I pressed the vive button below the touch pad.

I then deleted the HTC.UnityPlugin folder again, and imported the 1.8.1 package, and started seeing this behavior. I'm going to downgrade back to 1.8.0 and make sure I am not able to reproduce this behaviour with the previous plugin version.

Unity Version: 2017.2.0f3

**Comment by lawwong** [comment]
Thanks for the report. I also have this problem but not always.
Could you help try if adding "if (!IsInstance) { return; }" to line 92 ?
``` csharp
        private void Update()
        {
            if (!IsInstance) { return; }

            m_isUpdating = true;
            ...
```
Will commit the changes if this works.

**Comment by wirelessdreamer** [comment]
I was waiting yesterday for this but to pop up again before putting that change in, but didn't see it, I'll make a ticket update once I get back to a place where I'm seeing the issue happen, so I can test the fix in the correct conditions.

**Comment by wirelessdreamer** [comment]
I have not seen this issue in months.
