### ISSUE TITLE
VRTK support

### ISSUE THREAD

**Issue by subzero911** [ViveSoftware/ViveInputUtility-Unity#42]
Is it possible to combine your plugin with VRTK? I like their mechanics (levers, doors, climbing etc.) but I prefer your way of getting input (like "ViveInput.GetPressDown(HandRole.RightHand, ControllerButton.Trigger)" instead of VRTK event-driven input) and also your simulator is much better.

**Comment by dariol** [comment]
This has been investigated, unfortunately VRTK's architecture isn't as flexible (as of 3.x) but apparently VRTK now can use Unity events like we have been all along, so there should be a way to share code in both directions, however each utility or toolkit (much like other multiplatform tools) tends to manage cross platform support by managing the platform sdks (or "modules" in VIU) via wrapping making it difficult without having one wrap the other.
