### ISSUE TITLE
Wave SDK Controller does not follow headset

### ISSUE THREAD

**Issue by wdslatter** [ViveSoftware/ViveInputUtility-Unity#53]
Using unity 2018.2 and the latest wave SDK the controller remains in place even when the user physically walks in space. This occurs in the teleporting sample scene provided. It seems that the controller spawns at the location of the head, and then does not move? Not sure if I am missing something, but as it does not work in the sample scene I'm guessing there is a problem.

**Comment by lawwong** [comment]
Latest release (v1.9.0) should fix the problem.
Let us know if doesn't ~ thanks!

**Comment by wdslatter** [comment]
Perfect thank you, seems to be fixed!
