### ISSUE TITLE
Doesn't work with SteamVR Plugin 2.0

### ISSUE THREAD

**Issue by lawwong** [ViveSoftware/ViveInputUtility-Unity#54]
SteamVR Plugin 2.0 have lots of changes, we are working on supporting it.
Before we fix it, you will have to use the provious version
https://github.com/ValveSoftware/steamvr_unity_plugin/releases/download/1.2.3/SteamVR.Plugin.unitypackage

**Comment by mikelortega** [comment]
Good to know, I've just met this problem. Please, keep us informed, thank you!

**Comment by lawwong** [comment]
Fixing the namespace/API changes is easy...
But the critical issue is that v2 blocks the classic way to get controller button state
https://github.com/ValveSoftware/steamvr_unity_plugin/issues/128

**Comment by lawwong** [comment]
https://github.com/ViveSoftware/ViveInputUtility-Unity/tree/improve/steamvr200support
This branch fix the symbol and API changes issue.
But currently there are no input events yet (tracking only)

**Comment by chensida13** [comment]
does"SteamVR_Controller.Input((int)OpenVR.k_unTrackedDeviceIndex_Hmd).GetPressDown(EVRButtonId.k_EButton_ProximitySensor)" allow me to access proximity sensor? Seems it's always returning false during testing.

**Comment by chensida13** [comment]
> SteamVR Plugin 2.0 have lots of changes, we are working on supporting it.
> Before we fix it, you will have to use the provious version
> https://github.com/ValveSoftware/steamvr_unity_plugin/releases/download/1.2.3/SteamVR.Plugin.unitypackage

@lawwong I tried to use the package you provided to access proximity sensor input. It worked when I import the package to a fresh new unity project. But the same code did not work for me when I import the package to my existing project. Any idea how to solve this problem?

**Comment by wirelessdreamer** [comment]
Any idea on a timeframe for this adding support for button presses?

**Comment by lawwong** [comment]
SteamVR v2.0 and the new Input System will be supported in v1.10.0 release.
It's now on develop branch.
fadb710

**Comment by JeffBail** [comment]
I see "SteamVR Plugin v2.0/v2.1 support" in the v1.10.1 release notes; does that mean that this issue is fully resolved?

**Comment by wirelessdreamer** [comment]
SteamVR input is working in the currently released plugin, I've personally been actively using it for a while without issue.

**Comment by JeffBail** [comment]
Thanks, I was just wondering because this issue is still marked as open.
