### ISSUE TITLE
Daydream Controller Support

### ISSUE THREAD

**Issue by reneWoVR** [ViveSoftware/ViveInputUtility-Unity#56]
Hello together,

I tried to build a version for the mirage on the daydream platform with the VIU SDK. The HMD is working as expected but the controller is not tracking.

Maybe i missed something or is this a knowing bug?

I am thankful for any help.

**Comment by chengnay** [comment]
Can you share which version you are using for VIU SDK and Google VR SDK?

**Comment by reneWoVR** [comment]
Hey, yes sure, sorry I missed it in my previous post.

For both i used the latest version, for VIU its 1.9.0 and for the GoogleVR its 1.170.0.
I made a fresh installation for both sdks, unfortunately the controller is still not working. 
But the recentering and the home button from the controller IS working, only the transformation isn't mapping at runtime.

best greetings

**Comment by chengnay** [comment]
It seems GoogleVR SDK change the method of getting the controller position.
We will fix it ASAP.
Thanks for reporting this issue.

**Comment by reneWoVR** [comment]
Thank you for your effort

**Comment by lawwong** [comment]
We've pushed the modification.
Please help try if it works for you, thanks.
You can either download from latest commit or import from this patch package
[ViveInputUtility_v1.9.0.1patch.unitypackage.zip](https://github.com/ViveSoftware/ViveInputUtility-Unity/files/2445924/ViveInputUtility_v1.9.0.1patch.unitypackage.zip)
