### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by wdslatter** [ViveSoftware/ViveInputUtility-Unity#58]
Minor issue, but in preferences the check box for the 3dof virtual arms says 'Airtual' instead of virtual. (unless this is some jargon I haven't encountered before!)

![image](https://user-images.githubusercontent.com/25707699/47126671-72c33080-d23e-11e8-8392-a27fa1f2292d.png)

**Comment by lawwong** [comment]
Will fix in next update, thanks!
