### ISSUE TITLE
ToRole<TRole> constantly returns "Invalid"

### ISSUE THREAD

**Issue by ValakhP** [ViveSoftware/ViveInputUtility-Unity#6]
When using `ViveRoleProperty.ToRole<TRole>()`, it returns `Invalid` everytime.

I guess, that the problem is in line [167](https://github.com/ViveSoftware/viveinpututility-unity/blob/master/Assets/HTC.UnityPlugin/ViveInputUtility/Scripts/ViveRole/ViveRoleProperty.cs#L167):
`if (m_roleType != typeof(TRole) || roleInfo.TryGetRoleByName(m_roleValueName, out role))`

You have `m_roleValueName` parameter in method that is getting the role from Dictionary. After replacing it with `m_roleTypeFullName` everything works fine.

**Comment by lawwong** [comment]
Thanks, I actually missed a negation operator.
It should be
`if (m_roleType != typeof(TRole) || !roleInfo.TryGetRoleByName(m_roleValueName, out role))`
meaning that **returns invalid if role type not match or the value string not found in roleInfo**.

**Comment by ValakhP** [comment]
Oh, yeah. My bad. Anyway nice to have it fixed.
