### ISSUE TITLE
1.8.2，guideline far distance

### ISSUE THREAD

**Issue by Porco24** [ViveSoftware/ViveInputUtility-Unity#60]
if far distance is 2000, steamVR won't startup

**Comment by chengnay** [comment]
Can you provide more information listed below,
Which Unity, VIU and SteamVR plugin version?
Which scene did you try?

**Comment by Porco24** [comment]
sorry, i find out it just steamvr setting problem
my classmate carry my computer to other city and run the project,
he delete steamvr and install an other steamvr and did't set right,
sorry for this stupid problem :(
