### ISSUE TITLE
HTC vive touch pad inputs

### ISSUE THREAD

**Issue by junglee372018** [ViveSoftware/ViveInputUtility-Unity#65]
Hi 
I want to implement radial menu using the ViveInputUtility plugin. Tried so many ways to get touchpad axis values but couldn't get the values. 

Kindly help me in getting touchpad axis values.  

Thank you.

**Comment by chengnay** [comment]
Can you provide below information,
Which Unity version?
Which SteamVR Plugin version?
Which VIU version?

**Comment by junglee372018** [comment]
Unity v2018.1.6f1 and viveInputUtilities plugin v1.9.0

**Comment by chengnay** [comment]
Did you try out the UGUI example scene?
The scroll view you can simply use the trackpad to move around.

**Comment by junglee372018** [comment]
Yes, i have tried UGUI scene. In that scroll view is working automatically, no script attached to detect the touchpad inputs.
i want to read the touchpad vector values in order to work with radial menus [this](https://d2ujflorbtfzji.cloudfront.net/package-screenshot/16153132-c40b-45ca-a054-db6d37c60c41_scaled.jpg).

**Comment by junglee372018** [comment]
> I wrote a sample code that you can print out the axis data when you touch on the Touch Pad.
> if (ViveInput.GetPress(HandRole.RightHand, ControllerButton.PadTouch))
> {
> Debug.Log("padAxis = " + ViveInput.GetPadAxisEx(HandRole.RightHand));
> }
> 
> You can try to have above code place inside the Update() function and see if it works.

yeah, it worked.

Thank You
