### ISSUE TITLE
VIU 1.10 with Steamvr 2.0 - SteamVR Input generation locks up

### ISSUE THREAD

**Issue by wirelessdreamer** [ViveSoftware/ViveInputUtility-Unity#74]
Steamvr Input generation locks up with vive input utility, same version did not lock up without VIU

![image](https://user-images.githubusercontent.com/140221/50380162-9fc00500-062c-11e9-8d4d-2b9d10feec89.png)

**Comment by lawwong** [comment]
Seems like you have to focus on the "SteamVR Input Generation" window to let it continue to work?
Not sure if SteamVR plugin fixed this in v2.1.5.

**Comment by chengnay** [comment]
Are you able to reproduce this issue?
Can you roughly describe how you can reproduce this issue step by step?
Thanks!

**Comment by wirelessdreamer** [comment]
I just tried with a new project and didn't see this behavior. I'm not sure how to isolate what package is causing it, I found it issue when doing a test upgrade of my game to use SteamVR 2.0, Any ideas?

**Comment by chengnay** [comment]
Could you briefly describe how you upgrade your game to SteamVR 2.0?
Or are you able to make a sample game project that can reproduce this issue?
We would want to know how to reproduce and fix this issue ASAP, thanks!

**Comment by wirelessdreamer** [comment]
I haven't been able to put together a clean project to how to get the upgrade to crash yet. i'll make and update later if I can reproduce it in a clean project.

**Comment by wirelessdreamer** [comment]
Current releases of SteamVR and VIU don't exhibit this behaviour
