### ISSUE TITLE
Vive Focus Unable to track

### ISSUE THREAD

**Issue by zealousappex** [ViveSoftware/ViveInputUtility-Unity#77]
In Unity using Vive Input Utility v1.10.1  causes the Vive Focus to freeze when running the examples.

I downgraded to  Vive Input Utility v1.9.0 and the example work again.

I'm running:
Unity 2019
WaveSDK-2.1.8
Vive Input Utility 1.10.1

**Comment by frg-kova** [comment]
Same problem, but most examples don't freeze, just one I tried, others render with camera being extremely shakey if you move your head so it's unusable. 
Please make this high priority and hotfix it.

Unity 2018.3
WaveSDK-2.1.8
Vive Input Utility 1.10.1

**Comment by chengnay** [comment]
@zealousappex @frg-kova Could you try the latest version VIU 1.10.2 unitypackage from GitHub. We just fix this issue.

**Comment by frg-kova** [comment]
I updated to 1.10.2 and still have the shaky camera issues. This might not be related to the freeze bug so feel free to create a new issue from this if needed. This happens on VIU example scenes also but is not as noticeable as when you have a bit larger scenes. If you stay still - not noticeable at all, but if you move your head that's when the view is shaking, like it's going back and forth a bit all the time.

HelloVR example from WaveSDK - works, 75 fps
HelloVR with ViveRig - doesn't work, also at 75 fps

Finally I added a bit of geometry to HelloVR so shake is clearly noticeable and made a script that switches between the two when you press trigger as a demo:
[http://temp.protopixel.hr/VIUCamShakeDemo.apk](http://temp.protopixel.hr/VIUCamShakeDemo.apk) (27MB)

It worked in 1.9.0 also, can you guys go through diff between 1.9.0 and 1.10.1 and take a look everything camera/rendering related?

Unity 2018.3.0f2
WaveSDK-2.1.8
Vive Input Utility 1.10.2

**Comment by frg-kova** [comment]
Any news on this? I can't be the only guy that wants to use VIU for Focus, right guys? ...err, guys?

**Comment by dariol** [comment]
Not at all - I use it for several projects and give workshops precisely on using VIU for Focus - I'm looking into the diffs to see what this could be. If you can update to 1.10.0, you can cherry pick this needed fix provided in 1.10.1 that addressed a freezing issue on the Focus: https://github.com/ViveSoftware/ViveInputUtility-Unity/commit/bf3c6c50ef7cb431dfea01a5b57ba659e15484cf

**Comment by frg-kova** [comment]
Confirming cam jitter issue resolved in 1.10.3

**Comment by zealousappex** [comment]
I apologize for the delay, I have not gotten the unit back to test. I will close the issue since it looks like its confirmed fixed by frg-kova
