### ISSUE TITLE
Knuckles EV3 Support

### ISSUE THREAD

**Issue by JeffBail** [ViveSoftware/ViveInputUtility-Unity#79]
I saw on the [input support page](https://github.com/ViveSoftware/ViveInputUtility-Unity/wiki/SteamVR-Input-System-Support) that only the EV1 Knuckles are supported. I'm working with EV3 and I think I can move forward; I was able to get the 3DDrag example to work by using the SteamVR developer bindings GUI to setup the trigger actions. I can probably press ahead and remap controls as I need them but I'm also just wondering when EV3 will be officially supported and if I can help out with development.

**Comment by castana1962** [comment]
Hi lawwong 
Sorry for my little English but I am working with SteamVR 2.0.1 and EV3, for it, Is this Steam utility SteamVR 2.0.1 and EV3 compatible?
Thanks
Alejandro

**Comment by lawwong** [comment]
Oh, I see.
By our design B key should bind to viu_press_01 and viu_touch_01 to get VIU work.
Anyway, if I'm right, controller type for EV3 Knuckles is just "knuckles"?
Then this patch [ViveInputUtility_v1.10.1_knuckles_binding_patch.unitypackage.zip](https://github.com/ViveSoftware/ViveInputUtility-Unity/files/2767091/ViveInputUtility_v1.10.1_knuckles_binding_patch.unitypackage.zip) should work.

Let us know if it works (or not), thanks!

**Comment by JeffBail** [comment]
I checked in VRModuleBase.SetupKnownDeviceModel and the deviceState.modelNumber is "Knuckles EV3.0 Left" which is accepted by s_knucklesRgx so it seems like it should work.

**Comment by chengnay** [comment]
@JeffBail @castana1962 The latest VIU (v1.10.6) from Asset Store supports Knuckles EV3 and Index controller. Let me know if you are still having issue.
