### ISSUE TITLE
HTC vive grab button click on pointer enter.

### ISSUE THREAD

**Issue by junglee372018** [ViveSoftware/ViveInputUtility-Unity#81]
Hi,
I want to keep pointer on a particular object and click grab button.
Grab button click alone is working. when i want to perform grab button click by placing pointer on gameobject it is not working.

my code is like this
public void PointerEnter(PointerEventData eventData)
{
Debug.Log("pointer enter true");
      if (ViveInput.GetPressDownEx (HandRole.RightHand, ControllerButton.Grip)) {
      Debug.Log ("Grab button pressed true");
      }
}

Kindly help me in getting this solved.

I am using Unity v2018.1.8f1 and VIU v1.9.0

**Comment by chengnay** [comment]
My quick suggestion to your problem should be have a flag to set to true when pointer entered, then in Update function, check for grip button pressed and the flag is true.

private bool isPointerEntered = false;

void Update()
{
    if (ViveInput.GetPressDownEx(HandRole.RightHand, ControllerButton.Grip) && isPointerEntered)
    {
        Debug.Log("Grab button pressed true");
    }
}

public void OnPointerEnter(PointerEventData eventData)
{
    Debug.Log("pointer enter true");
    isPointerEntered = true;
}

public void OnPointerExit(PointerEventData eventData)
{
    Debug.Log("pointer exit true");
    isPointerEntered = false;
}

**Comment by junglee372018** [comment]
Yeah did the same. But, I am trying to do this on gameobjects not UI.

![snap1](https://user-images.githubusercontent.com/44200667/51238247-834d8900-199c-11e9-9e91-68c3aa0faf50.JPG)

**Comment by chengnay** [comment]
Do you mind sending me a sample project that I can test on? Thanks!

**Comment by junglee372018** [comment]
I forgot to add "IPointerEnterHandler, IPointerExitHandler"

Now its working.

ThankYou very much
