### ISSUE TITLE
不要轻易使用（ DontDestroyOnLoad）

### ISSUE THREAD

**Issue by funylion** [ViveSoftware/ViveInputUtility-Unity#84]
写中文应该看得懂吧，这已经给我带来了很多麻烦。 
Pointer3DInputModule
  if (Active)
            {
               DontDestroyOnLoad(instance.gameObject);
            }

**Comment by chengnay** [comment]
@funylion 請問這是甚麼問題?

**Comment by funylion** [comment]
![default](https://user-images.githubusercontent.com/19399348/51662792-ea4bed00-1fef-11e9-9b1e-45f2e522ee9f.png)
（如图所示，我不知道为什么它自己会自动添加一个然后跟我原来场景的EventSystem冲突了，导致里面的UI功能失效。这个原本不是问题，不过在当我允许它重新载入场景的时候就发生了。我花了很长的时间去寻找，最后发现是由于多出了一个EventSystem。）
As shown in the figure, I don't know why it automatically adds one and then conflicts with EventSystem in my original scene, resulting in the failure of UI functions. This was not a problem, but it happened when I allowed it to reload the scene. I spent a long time looking for it, and finally found out that it was due to the addition of an Event System.

**Comment by funylion** [comment]
（如图所示，我不知道为什么它自己会自动添加一个然后跟我原来场景的EventSystem冲突了，导致里面的UI功能失效。这个原本不是问题，不过在当我允许它重新载入场景的时候就发生了。我花了很长的时间去寻找，最后发现是由于多出了一个EventSystem。）
 As shown in the figure, I don't know why it automatically adds one and  then conflicts with EventSystem in my original scene, resulting in the  failure of UI functions. This was not a problem, but it happened when I  allowed it to reload the scene. I spent a long time looking for it, and  finally found out that it was due to the addition of an Event System.



------------------ 原始邮件 ------------------
发件人: "ChengNan Yang"<notifications@github.com>;
发送时间: 2019年1月24日(星期四) 下午2:52
收件人: "ViveSoftware/ViveInputUtility-Unity"<ViveInputUtility-Unity@noreply.github.com>;
抄送: "鸿"<232288522@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ViveSoftware/ViveInputUtility-Unity] 不要轻易使用（ DontDestroyOnLoad） (#84)




@funylion 請問這是甚麼問題?

**Comment by chengnay** [comment]
We will fix this in next release, thanks for reporting!

**Comment by funylion** [comment]
You're sure it's a BUG.Not only that, but it's also a probabilistic event.So it took me quite a long time to find it.（==！）
