### ISSUE TITLE
Remote role persistency

### ISSUE THREAD

**Issue by mrstruijk** [ViveSoftware/ViveInputUtility-Unity#85]
Hi! 

How can I make sure that one of the two controllers always has the same role? 
I would want to put a sticker on one of them saying "Left", and this one is then always the left-hand controller, regardless of in which order I turned them on. 

I was thinking I could check by serial number, but then how would I change the controller's HandRole based on that?

Thanks, 
Maarten

**Comment by wirelessdreamer** [comment]
see the example:
HTC.UnityPlugin/ViveInputUtility/Examples/7.RoleBindingExample

once you bind a role that controller will always have that role.

**Comment by mrstruijk** [comment]
Thank you!
