### ISSUE TITLE
Is there a method to get gameobject(such as HMD or Controller)?

### ISSUE THREAD

**Issue by wojiuxuihuan** [ViveSoftware/ViveInputUtility-Unity#98]
Sorry about all the questions:

1.In the sample script 'Teleportable', it has to find the vrcamera each time, and that's terriable.
So I wonder, is there a better way to get real gameobject such as HMD or Controllers via Singleton？Thanks.

2.Also, there are too many "Editor" Folders, I have to add Assembly Definition for them one by one, or it will show tons of error once I build the project, that's kind of annoying, can you please put them together?

3.When we start the game, which event can notify me when the HMD is in the right position, so that I can teleport to the specify pos?

**Comment by wojiuxuihuan** [comment]
Also, there are too many "Editor" Folders, I have to add Assembly Definition for them one by one ,that's kind of annoying, can you please put them together?

**Comment by wirelessdreamer** [comment]
1. Teleportable only does a find if those values aren't set, so if you set it on your own before you call the method, it will never do a find. my understanding is that the find is there as a fallback, but isn't intended to be the normal way to use it.

**Comment by wojiuxuihuan** [comment]
> 1. Teleportable only does a find if those values aren't set, so if you set it on your own before you call the method, it will never do a find. my understanding is that the find is there as a fallback, but isn't intended to be the normal way to use it.
Yes, but I wonder if there is a static Method to Find The specified Device, cos every platform has different parenting settings.
